### ISSUE TITLE
Custom metrics not showing in sidebar

### ISSUE THREAD

**Issue by danielkberry** [mozilla/experimenter#10009]
For [this experiment](https://experimenter.services.mozilla.com/nimbus/add-an-image-to-pdf-with-alt-text/summary), the custom metrics are not shown as clickable elements in the sidebar like the default metrics. 

Actual behavior: only default metrics are listed in the sidebar. 

Expected behavior: all metrics listed in the sidebar.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4179)

**Comment by danielkberry** [comment]
CC @mikewilli

**Comment by mikewilli** [comment]
This is partially fixed in #11535. It appears that the issue occurs for metrics which are missing the friendly name in the config, so the fix there was to use the metric slug as a fallback.

For some reason, I'm still seeing odd behavior -- the metrics appear initially but sometimes clicking on one of them makes them all disappear. I'm guessing there's another spot where this sidebar is getting created and we just need to do the same thing there.
