### ISSUE TITLE
Dependabot breaking when signed commits are required

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#1005]
If we enable signed commits for master, [as per this comment by @peterbe ](https://github.com/mozilla/experimenter/issues/932#issuecomment-468433485), then the dependabot commits are not mergeable, even though they report themselves as verified.  

The only thing related to this I can find is [this issue](https://github.com/dependabot/feedback/issues/81) but it doesn't seem to resolve it in any way.  For now I have disabled requiring signed commits.

**Comment by peterbe** [comment]
I think *you* just need to add your GPG key. https://help.github.com/en/articles/adding-a-new-gpg-key-to-your-github-account

**Comment by mythmon** [comment]
The key that you can add to your Github profile is your *public* key. It can be used to verify signatures, but cannot be used to create signatures. That's by design.

For dependabot's commits to be signed, dependabot would have to sign them with its own key. That's not something we can do. If we really want this, we need to take it up with dependabot.

On Normandy, we went through a similar situation. Some of our bots couldn't make signed commits. After talking with the security team, we opted to turn off the signed commit requirement. We sign our tags, which bundle up all the commits. That's enough.

Humans should still sign their commits, but bots not doing it isn't really a problem.

**Comment by jaredkerim** [comment]
I think our workflow is fine for now without strongly requiring signed commits so I'm going to close this.  If signed commits come up again we can revisit this.
