### ISSUE TITLE
Rollout should not accept enrollment days greater than experiment duration

### ISSUE THREAD

**Issue by yashikakhurana** [mozilla/experimenter#10119]
We have seen that if set enrollment days lets say 10 days and experiment duration 5 days, and then mark it as a Rollout, it will not pop the error that `the enrollment duration must be less than or equal to the experiment duration`, it will pop out once the user will try to increase rollout percentage. for example https://experimenter.services.mozilla.com/nimbus/backgroundupdate-enable-unelevated-installations-rollout-3-release/audience 
![image](https://github.com/mozilla/experimenter/assets/25848231/3b30f351-4de9-4d7e-a06c-11b976c65508)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4255)

**Comment by jaredlockhart** [comment]
I see how this happened, a combination of

* The values snuck in through cloning
* There was a bug where the enrollment period validation wasn't occurring for rollouts because the field was disabled and that is now fixed so there are experiments with invalid pairs of enrollment/duration that should not have been launchable but are live now

So we need to fix the invalid ones in the prod db and ensure this same invalid configuration can't be launched.

We can find and fix the broken ones with a query like

```py
NimbusExperiment.objects.filter(proposed_duration__lt=F('proposed_enrollment')).update(proposed_duration=F('proposed_enrollment')
```

So let's write that up as a data migration with a test.

**Comment by jaredlockhart** [comment]
We can do the data migration and the additional testing/validation separately, let's focus on the data migration first to unblock users.
