### ISSUE TITLE
Subscriber list and button not updated after unsubscription in duplicate tab

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#10245]
**[Prerequisites]:**

* Have an Experiment page opened in two tabs in the same or different browsers.
* Be subscribed to the experiment and have the lists updated.

**[Steps to reproduce]:**

1. On one of the tabs scroll down to the Overview section of the Summary page.
1. Click the "Unubscribe" button and observe the UI.
1. Navigate to the duplicate tab and wait a few seconds.

**[Expected result]:**

* The "Subscribers” list is updated and the “Unsubscribe” button is transitioned to the “Subscribe” state.

**[Actual result]:**

* The "Subscribers” list is not updated and all the emails are still displayed in the list, incorrectly displaying the “Unsubscribe” button as well.
* the “Unsubscribe” button is not transitioned to the “Subscribe” state.

**[Notes]:**

* The button is correctly updated after a page refresh.
* Attached a screen recording of the issue:
!notification.gif|width=1537,height=816!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-4348)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/57036">notification.gif</a>

**Comment by jaredlockhart** [comment]
So two things here

1) The summary page does periodically refresh automatically, but I recently changed it to update way less frequently because doing it every 30s was unnecessarily hammering the servers.  So in theory if you do the steps above and then wait up to 1hr they actually should synchronize.

2) Doing any kind of real time streamed update is a lot of work and I'm not sure is worth it for where we are.  The same is true for any other kind of updates, ie edits in the forms or changes in status, etc if you have two tabs open.

So I'm inclined to close this as wontfix.

**Comment by jaredlockhart** [comment]
These seem like duplicates to me:

https://github.com/mozilla/experimenter/issues/10244
https://github.com/mozilla/experimenter/issues/10245

**Comment by eliserichards** [comment]
I agree. This is a great catch by QA, but definitely a wont-fix 😄
