### ISSUE TITLE
The "Technical Risks Description" input field can wrongly be saved with empty spaces

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1082]
**[Affected versions]:**
- Firefox Release 66.0 and above
- Chrome 73.0.3683.75

**[Affected Platforms]:** 	 	
- All Windows
- All Mac 	 	
- All Linux

**[Prerequisites]:**
- You are logged with your LDAP account on the "https://experimenter.stage.mozaws.net/" website.
- Have an experiment created on the Experimenter stage website.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the created experiment from prerequisites.
3. Click the "Edit" button from "Risks" section.
2. Insert an empty space in the input field.
5. Click the "Save Draft and Finish" button and observe the behavior.

**[Expected result]:**
- The "! This field is required." error message is displayed.

**[Actual result]:**
- The experiment is saved.

**[Notes]:**
- Attached is a screen recording of the issue:
![TechDesc](https://user-images.githubusercontent.com/40061643/54685332-4417f180-4b1f-11e9-9b03-a54ffacebc92.gif)

**Comment by peterbe** [comment]
Curious. It's [not required](https://github.com/mozilla/experimenter/blob/40ff0dd39082aa11f3d730bbef56bb519d8e04fe/app/experimenter/experiments/forms.py#L614) but it doesn't say "Optional" under the label. 

[The template is probably busted](https://github.com/mozilla/experimenter/blob/40ff0dd39082aa11f3d730bbef56bb519d8e04fe/app/experimenter/templates/experiments/section_risks.html#L57-L60) because it if-statements on `experiment.risk_technical` but then attempts to display `experiment.risk_technical_description`.

**Comment by peterbe** [comment]
Ignore my comment above. I didn't really understand it properly. I have a solution coming in.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and is no longer reproducible on Experimenter stage "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website after the v2.28.0 stage deployment. 
Tested on Windows 10x64, Mac 10.14 and Arch Linux 4.16.6 x64.
