### ISSUE TITLE
Increase resource size for Fenix APK builder

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/experimenter#11161]
Currently we are using circleci's `medium` linux machines, we should increase this to large as the medium machines tend to run out of memory.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-4747)

**Comment by jrbenny35** [comment]
https://github.com/mozilla/experimenter/pull/11160

**Comment by data-sync-user** [comment]
➤ Benjamin Forehand Jr. commented:

I am still getting some issues so I asked Jon Buckley to open a ticket with circleci. It seems circleci is not respecting the no_output_timeout config option.

**Comment by data-sync-user** [comment]
➤ Jon Buckley commented:

Benjamin Forehand Jr. you can file a support ticket with CircleCI at https://support.circleci.com/hc/en-us/requests/new ( https://support.circleci.com/hc/en-us/requests/new|smart-link ) . One thing I’d try is seeing if the build output can add timestamps, or some other output. Maybe it’s still running into memory issues with the large instance, especially since it’s doing parallel compilation? Could try reducing parallelization to 1?

**Comment by data-sync-user** [comment]
➤ Benjamin Forehand Jr. commented:

Looks like I was able to solve this by using the xlarge resource class. Thanks Jon Buckley
