### ISSUE TITLE
Specify shield slug as part of study requirements

### ISSUE THREAD

**Issue by kirill-demtchouk** [mozilla/experimenter#1119]
Is there a way that the team in charge of running a given test in Firefox can specify the shield slug? Or part of the shield slug?

Having to re-confirm what the shield slug is for a given test _after_ that test gets released makes it difficult to build reporting before a study is released and makes it difficult to confirm enrollment is proceeding as expected.

**Comment by jaredkerim** [comment]
@kirill-demtchouk Yep you've anticipated the next set of changes coming to Experimenter!  You're right that right now it's difficult to identify and track the shield slug for an experiment, but the changes we're implementing *right now!* will make that much easier.  Soon Experimenter will generate the shield slug as the experiment moves into the 'ready to ship' state, and then store it and transmit it to normandy so that it's consistent between experimenter, normandy, monitoring, telemetry.  Then experimenter will be able to predict the dashboard URLs while your experiment is live.  So stay tuned over the next few weeks and I think it should address the problems you're having.

**Comment by jaredkerim** [comment]
This is fixed by https://github.com/mozilla/experimenter/issues/498
