### ISSUE TITLE
End date should reflect Completed date from Normandy

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#1166]
After an experiment is complete, the change log records the actual dates the experiment started and ended, and so we should update the timeline section with separate 'proposed timeline' 'actual timeline' sections so it's clear to see when and how long the experiment actually ran for.

**Comment by shell1** [comment]
Does the Pause and End update once an experiment launches?  So based on the duration - adjust base on when it goes live?  

Asking because right now managing the "pause" and "end" pipeline is a complete nightmare and highly error prone.  

If there was an 'actual timeline' that had when an experiment actually launched - with calculated pause and end dates - we could:
filter for experiments with pause and end dates between the last change window and current change window (those 2 date options) for all the work that needs to happen.

**Comment by shell1** [comment]
Looks like the pause and end dates are being recalculated once the experiment launches (and changes to actual) and updated on the Listing Page too.  Looking at this experiment https://experimenter.services.mozilla.com/experiments/process-priority-manager-on-windows/ that had the wrong proposed original timing right before launch - experimenter is now showing the right calculations based on the actual launch.  (below screenshot with original timing)
<img width="727" alt="Screen Shot 2019-04-15 at 10 40 04 AM" src="https://user-images.githubusercontent.com/8192232/56672297-10bf0a00-666b-11e9-9381-1c7387a70b34.png">

we'll have the completed date from Normandy - it would be a nice to have if that date overwrote the current calculated "end" date.  

The pause isn't so vital for records = outside of scheduling changes -so the calculated is fine for that one.

**Comment by jaredkerim** [comment]
So we need to go into here:

https://github.com/mozilla/experimenter/blob/master/app/experimenter/experiments/models.py#L349-L365

and update all those methods to behave the same way as:

https://github.com/mozilla/experimenter/blob/master/app/experimenter/experiments/models.py#L342-L347 

ie the real end date is the date that a changelog exists from LIVE -> COMPLETE

and then update the duration method to use the real end and start dates after the experiment has ended.

We can't do this for the 'real' enrollment end date becuase experimenter doesn't track when enrollment actually ends, so we'll just have to use the proposed enrollment duration in all cases.
