### ISSUE TITLE
The "Experiment Bugzilla Ticket" isn't created for experiments on the new stage website

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#1201]
**[Affected versions]:**
- Firefox Release 66.0.3 and above
- Chrome 74.0. and up

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have an Draft experiment created on the "https://stage.experimenter.nonprod.dataops.mozgcp.net/" website.
- You are logged in your LDAP account.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://stage.experimenter.nonprod.dataops.mozgcp.net/".
2. Open the experiment from prerequisites and click the "Ready for Sign-Off" button.
3. Refresh the page and observe the "Tickets" section under the experiment's title.

**[Expected result]:**
- The "Experiment Bugzilla Ticket" is displayed in front of the "Data Science Bugzilla Ticket".

**[Actual result]:**
- Only the existing tickets are displayed.

**[Notes]:**
- Attached is a screen recording of the issue:
![Ticket](https://user-images.githubusercontent.com/40061643/56651473-c1d89b00-6691-11e9-8a51-1454bf957faf.gif)

**Comment by jaredkerim** [comment]
This is still being caused by errors on the Bugzilla side that are out of our control and should be covered by https://github.com/mozilla/experimenter/issues/1083

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is only partially fixed as it is still fully reproducible with add-on experiments in the "Signed Off" state which have only the required fields from the “Overview” section filled.

And it is intermittently reproducible with:
- Pref experiments which have only the required fields from the “Overview” section filled
- Add-on experiments which have the required population area filled
- Experiments which have all the fields from all sections filled
- A previously archived experiment in the "Draft" state

**Comment by jaredkerim** [comment]
Figured this out, stage and dev were sharing a redis instance and consuming one anothers tasks so they were intermittently failing regardless of which data was present.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and is no longer reproducible on Experimenter stage "https://stage.experimenter.nonprod.dataops.mozgcp.net" website.
Tested on Windows 10x64, Mac 10.14 and Arch Linux 4.16.6 x64.
