### ISSUE TITLE
Add a field for a link to addon code for addon experiments

### ISSUE THREAD

**Issue by sunahsuh** [mozilla/experimenter#1218]
I'm currently investigating some data issues with a particular experiment and it'd be _very_ helpful to have a link to this particular addon's code, especially since extra metrics are often documented there.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-76)

**Comment by shell1** [comment]
Hi Sunah, 

Is knowing the add-on code a common need you have for most studies or the exception?  We recently added the "engineering manager contact field" on the first page - to simplify finding the contact for all one-off engineering questions that come up.

We want Experimenter to collect the minimal information needed to run most studies.  We want as small a hurdle as possible, to get the info provided completely and right.  

If this is something you need for most experiments - I'll work with you to adapt the intake tool for them all.  If this is an exception issue only hit once in a while, it's better to contact the engineering manager for that question instead of adapting the intake form.

I'm going to check with QA also on how often they need the add-on code during testing.  If it's the exception - no change.  If it's common - will look at adding that field.

**Comment by shell1** [comment]
going to hold off any more changes in Add-on, until seeing what Rehan is looking at for add-on signing flow.
