### ISSUE TITLE
change the wording of "QA Requested" checklist item and add link

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#1219]
Change the wording of "QA Requested" to "QA Jira Request Sent" and make the "Jira" be a hyperlink to https://moz-pi-test.atlassian.net/servicedesk/customer/portal/9

**Comment by Softvision-RemusDranca** [comment]
@shell1  Please take in consideration that not all users have Jira accounts because of limited licenses and they won't be able to access the portal. Not sure how to mitigate this, but we had complaints regarding this matter where people encountered a screen saying "You don't have permission to view this request".
