### ISSUE TITLE
Searching is not working as expected

### ISSUE THREAD

**Issue by bsurd** [mozilla/experimenter#1409]
**[Affected versions]:**
- Firefox Release 67.0.1 and above

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- You are logged in your LDAP account on the [Experimenter](https://stage.experimenter.nonprod.dataops.mozgcp.net/) website.

**[Steps to reproduce]:**
1. Click in the Search Experiments field under Filter Experiments.
2. Search for eg. 65.

**[Expected result]:**
- All experiments containing the string are displayed.

**[Actual result]:**
- No result is displayed.

**[Additional Notes]:**
- If you search for 65.0 only one experiment is returned.
- If selecting **Firefox 65.0** in the **All Versions** field all experiments on 65 are returned.

**Comment by jaredkerim** [comment]
Right now you can filter for exact versions using the drop downs on the right.  The search text box only searches the text fields.  I understand the confusion about not being able to type in a version and get a bunch of exact matches, but I think since you can already do what you're describing using the drop downs we're going to mark this as a wontfix and if this comes up more in the future we can revisit it.
