### ISSUE TITLE
Add env var for worker refresh rate

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#1739]
We have the workers hardcoded to update from normandy every 5 minutes (300s) but now that we have the capability to test the entire workflow locally it's annoying to wait 5 minutes, it should be an env var so we can set it to something like 30s if we want to.

**Comment by datavizard** [comment]
Is this issue still pending? I am interested in helping out if this needs to be done.

**Comment by tiftran** [comment]
Hi @datavizard!
Yes, this issue is still pending if you would like to work on this. This would involve changing the `schedule` value in `CELERY_BEAT_SCHEDULE` from `settings.py`
 Start by forking the repo, then create a branch in your fork and follow the instructions in the README to get the docker environment setup and your tests passing using `make check`

**Comment by tiftran** [comment]
Hi @datavizard, will be picking this up. Thanks for taking interest in experimenter, please feel free to continue to look around for issues, if you're still interested :)

**Comment by datavizard** [comment]
Hello @tiftran, was not available earlier. Do you need help in any other low priority/beginner issues? I'll be happy to help.

**Comment by tiftran** [comment]
Hi @datavizard would you be interested in working on https://github.com/mozilla/experimenter/issues/1985? Please kindly let me know and I'll add more instructions/context for it.
