### ISSUE TITLE
Add react tests

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#1789]

**Comment by jaredkerim** [comment]
Let's try to copy the way https://github.com/mozilla/avocado/ does it

**Comment by jaredkerim** [comment]
From feedback from @rehandalal we should be using

https://github.com/testing-library/react-testing-library

instead of Enzyme to mount and interact with components during tests.

The official docs here recommend the same tool:

https://reactjs.org/docs/testing.html

So let's try setting that up and using that, and I'd like for this ticket to cover adding 1-3 simple tests for each component we have now that checks that

1) given some expected props it renders
2) for components with major interaction points (add/remove branch in BranchManager,  submit successully, submit with errors in DesignForm) we add a couple basic tests for these cases.

We should to avoid being exhaustive at this stage because we have to make time to work on the new intake types that will depend on this in the coming weeks.  Once everything's in place we can go back and figure out where we can add more detail.
