### ISSUE TITLE
Pre-existing experiments don't have a control branch

### ISSUE THREAD

**Issue by tiftran** [mozilla/experimenter#1852]
Place holder to see what will need to be done. Initial investigation seems to suggest this was broken v2.38 or earlier. Currently in v2.40 since there may not be a control branch, UI displays "branch 0" instead
![Screen Shot 2019-10-30 at 2 40 10 PM](https://user-images.githubusercontent.com/25379936/67905385-63074900-fb2e-11e9-9d72-7770712ec04a.png)

**Comment by jaredkerim** [comment]
This indeed became the case, we haven't dug into what created this situation, but now that we've landed the new react design page that DOES explicitly set a control, it shouldn't be a problem going forward.  I had to go into existing editable experiments and flag control branches by hand so that they worked with teh new react page that does expect a control to exist.  We can revisit in the future whether we want to just throw out the control flag in the future.  Closing this for now.
