### ISSUE TITLE
Allow only approved people permissions to click the "Firefox Peer Sign-off" box

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#1891]
Get a list of peers who should have the rights to sign off on peer reviews. 

This isn't a requirement - if @mossop doesn't want it - but we do it for very important sign-offs like QA and Relman. 

Peer review is only required if they answered "yes" to the risk question, indicating that their code was especially risky in the way that encouraged peer review.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/EXP-112)

**Comment by Mossop** [comment]
Been holding off replying here because I am trying to publish an updated list of peers for Firefox as a whole, but that is getting stuck in some higher-level arguments about the nature of the modules.

In general this has a list of everyone allowed to peer review code for the front-end of Firefox: https://wiki.mozilla.org/Modules/Firefox. They are all trusted to say no to reviews that are outside of their areas of expertise.

For experiments that include new experiment APIs the webextensions team would also like to take a look over the API (they may also be able to do the entire review). These are: Shane Caraveo, Tomislav Jovanovic, Luca Greco, Kris Maglione, Andrew Swan and Rob Wu. Shane is the owner of that area so can help you find a specific person if needed.

**Comment by shell1** [comment]
not needed
