### ISSUE TITLE
Swapping Variants Causes Design Form do nothing on save

### ISSUE THREAD

**Issue by tiftran** [mozilla/experimenter#1894]
Seen in V2.39.0 swapping variants will cause the form to do nothing , text fields turn green
![image](https://user-images.githubusercontent.com/25379936/68334842-40c27d80-0090-11ea-99ab-e696fea54658.png)

**Comment by uhlissuh** [comment]
this issue is on 2.39, but there's also this issue on 2.40. our feeling is that this stems from editing the variants in place instead of deleting and recreating them. when on 2.40, you can see the server throw a 500 with a duplicate key error of 
```django.db.utils.IntegrityError: duplicate key value violates unique constraint "experiments_experimentvariant_slug_experiment_id_ea0bf951_uniq"
app_1     | DETAIL:  Key (slug, experiment_id)=(dog, 2) already exists.```

but on 2.39, the server responds with 200... as if there is no error.. which is super confusing.

**Comment by tiftran** [comment]
After some more tinkering, https://github.com/mozilla/experimenter/blob/master/app/experimenter/experiments/forms.py#L382 is why errors aren't showing up. We don't handle the case where `all([f.is_valid() for f in alive_forms])` in an event where an alive form or few are not valid

**Comment by jaredkerim** [comment]
Let's find out from felix what his use case was for trying to swap but also at minimum we should definitely throw an error for this.
