### ISSUE TITLE
Add outcome questions to results section

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2283]
In service of monitoring the overall health/performance/quality of the delivery platform over time, I think we should track some basic delivery outcomes in experimenter for each delivery so that we can visualize them over time.  

Tentative proposal of outcome questions to add to results section (as a checklist) (subject to review)

- [ ] Did this delivery fail to launch at the expected time?
- [ ] Did this delivery require any restarts after it launched?
- [ ] Did this delivery fail to enroll the expected number of users?
- [ ] Did this delivery end before it was expected to?
- [ ] Did this delivery fail to generate usable data?
- [ ] Did this delivery complete successfully but fail to meet its intended outcome (edit: Did this delivery end prematurely)?

Edit: Maybe we could also have a notes field for any additional information

**Comment by jaredlockhart** [comment]
Because this relates broadly to the quality monitoring effort for the delivery platform, I don't believe this is actionable without further review/feedback.

**Comment by shell1** [comment]
this looks good except for the "fail to generate usable data"... I think that is going to be confusing with "were the right probes there" "were the right questions even asked" "did the experiment design answer your questions" "were the results available quick enough to be usable for their needs".  

The other questions I think capture the way delivery specifically can go wrong.  the last question is covers the delivery aspects well - of not meeting intended outcomes.

**Comment by tdsmith** [comment]
Thanks for the tag! Some thoughts:

>  Did this delivery fail to launch at the expected time?

Does this encompass, like, "QA took longer than we expected" or just "we were green but didn't ship"?

A couple of these seem to reflect problems that other teams are responsible for, which is fine if that's your intent:

>  Did this delivery fail to enroll the expected number of users?

I think this would usually be a data science error in the absence of some other mistake.

>  Did this delivery fail to generate usable data?

This seems like it comments on the engineering of the intervention itself. (I see Shell's concerns but I'd attach those concerns to "fail to meet intended outcomes" more than "usable data," but maybe our differing opinions are a signal.)

**Comment by shell1** [comment]
I'm hoping "did this delivery fail to launch at the expected time" is just "we were green but didn't ship".   But I bet this is also gets checked for "we missed getting VP sign-off - so this didn't launch on time" or "failed QA and had to fix bugs - so didn't launch on time".

+1 on the enrolling question not being quite right for delivery specific.  "Did this delivery have a recipe error" would work.  people know when that happens.

In general - I think this thread is AWESOME to have started @jaredlockhart - but maybe needs a doc for comments and a meeting to hash out easier?

**Comment by shell1** [comment]
Did this delivery fail to launch at the expected time?
_Did this delivery have recipe errors?_
Did this delivery require any restarts after it launched?
Did this delivery have low user enrollment issues?
Did this delivery end before it was expected to?
Did this delivery fail to generate usable data?

box to elaborate


Did changes (features, performance, UX, etc.) enter Firefox because of this delivery? 
Was the data required to prove or disprove your hypothesis (which may include a null result) obtained?
Did this delivery provide the confidence needed to more forward?
Did this delivery help understand/measure the impact of this feature?

box to elaborate

**Comment by shell1** [comment]
help should go here https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-ResultsandFeedback

the words in the box after the sections should say "optional space for more details

**Comment by jaredlockhart** [comment]
@shell1 One thing that occurred to me is if you think about a given question being framed positively or negatively

Positive:  Did this delivery provide the confidence needed to move forward?
Negative: Did this delivery fail to provide the confidence need to move forward?


If you frame the question positively, and then nobody ever comes to this section to fill it out, then the box is empty, which is a confusing signal.  Did it not do the good thing or did they just not get around to answering it?  Or if they answer some questions but don't answer others and then save the page, then we can't distinguish between those cases.

Whereas if the question is framed negatively and nobody ever gets around to answering it, then the case of 'either it went fine or they didn't answer' is clearly distinguished from 'it definitely went bad' if they do select the check box.

**Comment by shell1** [comment]
I suspect we could debate wording for hours :).  I was tempted to write out all the "did this fail to" phrasings entirely - as that forces a double negative - which is inherently not clear.  

I finally settled in just making all the questions so that "yes" indicates a change /something to report. 

In the top questions that is reporting an issue.  In the bottom questions that is reporting a learning.

If they don't answer "yes" to anything - that is a redflag to check see if they 
1. just didn't fill it out - or
2.  if they are saying nothing went wrong - but we didn't get any value 

If it's 1 - I can say "please fill out" - if it's 2 it was likely a low value delivery effort
