### ISSUE TITLE
rollout incorrectly asking for VP signature

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#2294]
This rollout only had "technically risky" as yes- but said it required a VP sign-off.  I don't believe I had checked off anything as yes and then changed my answer - but can't remember.
  
https://experimenter.services.mozilla.com/experiments/increasing-normandy-spreading-out-changes-from-15-minutes-to-60-minutes/

It shouldn't do that based on how that risk question was implemented https://github.com/mozilla/experimenter/issues/868

I tried recreating in stage and could not  - so maybe I did something weird that got me into this state (but I can't think of what) - https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/testing-vp-sign0ff/  https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/klhhjk/

**Comment by tiftran** [comment]
@shell1  I looked back into the change log and i found...
![Screen Shot 2020-02-26 at 10 24 29 AM](https://user-images.githubusercontent.com/25379936/75375264-9494e480-5882-11ea-8837-4225d95bb51c.png)

And since https://github.com/mozilla/experimenter/issues/2261 was implemented, the risk question is hidden for this rollout, but it's still technically checked as yes.

**Comment by shell1** [comment]
AH - OK.  sounds like total edge case then where I was half done with it.  We don't have to fix is only weird half done rollout drafts could have gotten here..  @tiftran

**Comment by tiftran** [comment]
Closing issue then, since this is an edge case
