### ISSUE TITLE
Bugzilla API changes

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2308]
Emma recently sent an email about changes to the bugzilla API. We should review them and make sure all our i's are crossed and t's are dotted.

**Comment by tiftran** [comment]
@jaredlockhart is there new docs about the changes?

**Comment by shell1** [comment]
## Summary ##

During 2020, the Bugzilla team will be making several changes to improve security and performance for our users who rely on APIs and automation. We want you to know about them so you can start preparations.
## AutoNag  ##

AutoNag is a service which runs a Bugzilla query and then takes actions on the results. It’s used to notify teams about untriaged bugs, close intermittent test failures, clean up bugs, and other tasks. 

You can write your own scripts, following the guidelines in the repository, or file an issue to request one.

If you want to set up a rotation of people to triage a component, AutoNag will enable that as well. You need to set up a Google Calendar or JSON file with a schedule of people triaging bugs first.

If AutoNag does not meet your requirements and you run your own bots and scripts, please take note about upcoming changes.
- https://wiki.mozilla.org/Release_Management/autonag- https://github.com/mozilla/relman-auto-nag
## Bot guidelines ##

If you run a script or bot that uses the Bugzilla API, make sure it is in our registry.

Check the registry page because it has requirements we expect all bots and scripts to follow by mid-2020: including standard naming, using api keys, and our REST interface. 

- https://bmo.readthedocs.io/en/latest/api/index.html- https://wiki.mozilla.org/BMO/Bot_Registry
If you use our old APIs you need to know about their retirement.

## Old interfaces going away ##

We plan to shut down the JSONRPC (https://bugzilla.mozilla.org/jsonrpc.cgi), XMLRPC (https://bugzilla.mozilla.org/xmlrpc.cgi), and BzAPI (https://bugzilla.mozilla.org/bzapi/) interfaces by the end of June, 2020.

If you use one of these, you will need to update your code to use REST. That interface is documented, and if you find problems or issues with it please file a bug.

- https://bmo.readthedocs.io/en/latest/api/- https://bugzilla.mozilla.org/enter_bug.cgi?product=bugzilla.mozilla.org&component=API
This would be a good time to move the definition of the base URL you use to access our API to a configuration in your applications using it.
- https://bugzilla.mozilla.org/rest
Questions?
Please seek the BMO team out on Slack and Matrix.
Thanks, 

Emma Humphries, on behalf of the BMO team

**Comment by tiftran** [comment]
AutoNag - not applicable
Bot guidelines - already registered [here](https://wiki.mozilla.org/BMO/Bot_Registry)
Old interfaces going away - don't believe we're using any of these
