### ISSUE TITLE
Use computed dates in CSV rather than proposed

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#2711]
We should be using the computed start/end/duration/enrollment duration values in the CSV reports otherwise all the dates will be wrong.

**Comment by shell1** [comment]
Question - what happens if there isn't a computed date?  

So for when stakeholders want to see coming experiments?  Will it the proposed date if there is no computed date?  Or should we add that as another column for proposed date at the end?  We can pull it earlier if they are looking for future stuff.

**Comment by tiftran** [comment]
@shell1 So how I currently have it is similar to what's displayed in experimenter. Live and post-live experiments should have the actual start date, while experiments that haven't reached Live has a proposed start date. Same case with proposed duration/duration and completed and non completed experiments. 

Was wondering if there's anything that might be concerning of if proposed and actual are mushed into the same column?

**Comment by shell1** [comment]
@tiftran that is perfect that they are in the same column.  what you proposed is the solution I was hoping for.  thank you!
