### ISSUE TITLE
Experimenter failed to create a Bugzilla Ticket for your experiment

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#2937]
Per https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/rapid/rapid-333/edit/

I'm trying to create a new rapid experiment and clicked Save then Back buttons, and I'm seeing an odd notification at the top saying:

> _"Experimenter failed to create a Bugzilla Ticket for your experiment. Please contact an Experimenter Administrator on #ask-experimenter on Slack."_

I'm not sure what the Bugzilla message is about. I haven't submitted the experiment for review. Just created it, clicked the Save button, then clicked the Back button to edit the experiment.

Not sure when the ideal time to submit the Bugzilla ticket would be. This currently feels too early, but I could see creating a Bugzilla ticket after submitting for review/approval or after the experiment has been approved (do we want a bunch of Bugzilla tickets for rejected experiments? maybe.)

---

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/86059749-39cdee00-ba18-11ea-9a4b-9783066eb618.png)

**Comment by jaredlockhart** [comment]
Filed this: https://bugzilla.mozilla.org/show_bug.cgi?id=1646103

**Comment by jaredlockhart** [comment]
@pdehaan Yeah, in the old workflow it would go

Draft -> No bugzilla ticket
Ready for Signoff -> Bugzilla ticket Created
Ready to Ship -> ....
Send to Normandy -> Recipe created including bugzilla ID


In the new workflow it's

Draft -> Bugzilla ticket created
Request Approval -> Recipe generated and sent to remote settings for review


Becuase you need the bugzilla ID to generate the recipe, there's kind of no choice but to generate it right at the start now since we took out all those extra steps.  I think we'll have to leave it this way until we have a very clear reason to have to change it.  I'm gonna close this ticket for now, with the work tracked for fixing the API key in the bugzilla ticket and the design considerations as being reasonable for now.
