### ISSUE TITLE
Prepopulate the`Firefox Version`field for Nimbus

### ISSUE THREAD

**Issue by AnaMedinac** [mozilla/experimenter#2948]
Is it possible to pre-populate the `Firefox Version` field in the rapid experiments form with the current Firefox Version. This way it's automatically filled in and the user doesn't have to worry about this field unless they're concerned with the version.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-193)

**Comment by jaredlockhart** [comment]
@AnaMedinac Right now there's no way to determine what the 'current firefox version' is inside Experimenter, so if you wanted it to behave that way I'd suggest sticking a placeholder in that literally says 'Current Version' and links out to the release calendar.

Side note, I'm confused about what this field does.  Is it the minimum or maximum version?  Does it correlate to the channel specified in the audience?

**Comment by jaredlockhart** [comment]
Let's close this and go with users being intentional about which specific versions they intend to target.

**Comment by pdehaan** [comment]
(formerly https://github.com/mozilla/experimenter/pull/3043#discussion_r455333538)

Currently looks like:

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/87593202-f0c89b80-c69f-11ea-8312-8d2d4bbe62ab.png)

I think my concerns are if Firefox 83 is release, we'd have ~6 old builds at the top of the list that don't make sense. Or each new experiment would always have to select the correct Release version from a dropdown. Or if you mistakenly select "Firefox 94.0" from the dropdown (because reasons), the experiment would launch (if not caught+rejected by an operator), but nothing would happen because even after your enrollment+test period, that version would never be in scope and you'd presumably get no results back.

But yeah, maybe its too tricky to scrape the list of current trains from https://whattrainisitnow.com/ (or the upstream https://product-details.mozilla.org/1.0/firefox_versions.json which is where they apparently fetch from). Having a pseudo-dynamic list of dropdown values adds a lot of weird edges.
I just didn't know if a select list with only 3 options:

- "**Release** _Firefox 78.0_"
- "**Beta** _Firefox 79.0_"
- "**Nightly** _Firefox 80.0_"

... would make it easier an easier UX for experiment submitters. Since we only ever show 3 options, "Release" would always be the first/default option and what submitters would want 99.99% of the time anyways.

**Comment by jaredlockhart** [comment]
Blocked on design input from @AnaMedinac and @k88hudson

**Comment by k88hudson** [comment]
I agree with @AnaMedinac's original comment that we should set the default value to the current release. I think it would also be good to indicate that in the UI as well (maybe the words "current release"?).

What other design input are you looking for? Would it be doable to read that value https://product-details.mozilla.org/1.0/firefox_versions.json?

**Comment by k88hudson** [comment]
@k88hudson I will discuss options with @jaredlockhart in our next pairing session
