### ISSUE TITLE
Add rejected state to Experiment

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#3001]
If an experiment gets rejected in remote settings, we need to pick up the rejection reason and add it to the experiment and mark it as status: REJECTED.  Finally the long forgotten REJECTED state will have its comeuppance.

**Comment by pdehaan** [comment]
Where would an admin/operator enter a rejection reason?
Is there a UI in RS? Or would this be some form field within Experimenter UI?

Once my experiment is rejected, is there any way to fix+resubmit? Or do I have to recreate from scratch as a new experiment and submit (and possibly have to create a new name/slug since I'd now potentially get a slug collision on my first rejected experiment)?

**Comment by jaredlockhart** [comment]
There's UI in kinto admin that we'll be using for MVP1, and then I imagine we'll be building that right into Experimenter in MVP2.

And yeah I expect the workflow is once rejected, you can edit and resubmit.

**Comment by jaredlockhart** [comment]
Just do this in here: https://github.com/mozilla/experimenter/issues/3003
