### ISSUE TITLE
Rapid detail page state for rejected experiments

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#3003]
If a reviewer rejects an experiment in remote settings, a rejection reason will be entered in the remote settings admin.  We can then mark the experiment in Experimenter as rejected and show the rejection reason, and in theory the owner should be able to modify their experiment accordingly and then resubmit for review.  We'll need workflow and UX/UI for this.

**Comment by AnaMedinac** [comment]
Here is a screen shot of the Rejected state:

<img width="644" alt="image" src="https://user-images.githubusercontent.com/22782298/87333048-8df1cb80-c50a-11ea-8140-eaab216870e3.png">

I've updated the Figma to reflect the states, here: https://www.figma.com/file/5SLa07XqQb0ttB1ay1gami/WIP-Platform-Exp?node-id=214583%3A0

Also as reference here is the user flow with the states: https://miro.com/app/board/o9J_kpOgUTE=/

**Comment by jaredlockhart** [comment]
So
- Add a `rejected` status to experiment statuses
- Add it to the state transitions for rapid experiments
- Update the `check_kinto_queue` task becuase i think the way this will have to work is
  - experiment gets pushed to remote settings
  - reviewer rejects
  - now there is nothing in the queue but if we push immediately we lose the rejection message so you'll have to FIRST check if there's a rejection message, create a changelog that sets status to rejected and put the rejection message in the changelog, then proceed to pushing hte next one into the queue
- Add `rejection_reason` to V3 API that comes out of the REVIEW -> REJECTED changelog
- Update detail page to show rejection reason and allows for editing which then sets it back to DRAFT

**Comment by jaredlockhart** [comment]
After I land https://github.com/mozilla/experimenter/issues/3146 we should also omit rejected experiments from V4 API

**Comment by pdehaan** [comment]
If the experiment is rejected (meaning it never went live, presumably), it probably doesn't make sense to display the "Results" block of heading+text since there will never be results.

The "Back" and "Request Approval" navigation probably only makes sense if users can go back to edit the experiment and correct the issue that caused the experiment to be initially rejected and resubmit.

**Comment by jaredlockhart** [comment]
@pdehaan exactly

**Comment by pdehaan** [comment]
And since this is the UI topic, I can probably ask here...

Can a rejected experiment be fixed and resubmitted? Or once it's rejected is it a dead and and a user would have to redo the experiment from scratch (and now get a name/slug collision)?
If you can't edit+resubit, I propose we hide that "Back" "Request Approval" navigation completely because it's confusing.
If you _CAN_ edit+resubmit, i think we'd need to delete/hide that rejected review feedback text when they resubmit to avoid confusion. Either the updated experiment would be awesome and that old text is unneeded, or the updated experiment would be re-rejected and would get a new rejection reason added via Remote Settings.
