### ISSUE TITLE
Link to experiment results takes me to a fancy 404 page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#3142]
Q: Should https://metrics.mozilla.com/protected/experiments/raspberry_pie.html links work yet? Currently getting an nginx 404, but wasnt sure if the plumbing was hooked up yet. 

**Tim Smith** says on [Slack](https://mozilla.slack.com/archives/C011MC5EB0V/p1595965245176900): 
> only if an experiment has launched recently on prod and the enrollment period is over
> so “maybe”
> the list of things that does exist is at https://metrics.mozilla.com/protected/experiments/

**Peter deHaan**:
> interesting, thanks… wondering if that means every recently launched/approved experiment would show a 404 for that page until the end of [~7 day?] enrollment period.

**Tim Smith**:
> For now, if we start showing that link immediately, yeah. We could have partybal throw up a placeholder pretty easily but only on a nightly cadence (this system is very janky)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-205)

**Comment by jaredlockhart** [comment]
Should this ticket be filed here or in the partyball repo?

**Comment by pdehaan** [comment]
:shrug:

I wasn't sure if the solution was not to display the link in Experimenter until the results are ready (which is probably just a HEAD prefetch on the metrics.mozilla.com experiment URL to see if we get a 200-vs-404), or if we just leave it to Partyball to set up a prettier 404 page and possibly just have a 404ing link on Experimenter for <24h (until the cron nightly script does whatever jank it needs to).

**Comment by tiftran** [comment]
Is there a stage version of https://metrics.mozilla.com/protected/experiments/ maybe, that we could use for stage experimenter?

**Comment by tdsmith** [comment]
It's hard for partybal to address this correctly since it's just a pile of static HTML and I don't control the web server.

A few things that we could reasonably do:
* Just accept this
* Experimenter could suppress the link out until the enrollment period ends (doesn't address historical experiments)
* Partybal could write out stubs for live experiments without results (doesn't address historical experiments)
* Ask data ops to stand up a custom 404 page for this path

Prefetches probably won't work because the results pages are behind SSO.

> Is there a stage version of https://metrics.mozilla.com/protected/experiments/ maybe, that we could use for stage experimenter?

There is not.
