### ISSUE TITLE
Experimenter formating slugs in a way that CFR xman consumes

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#3287]
Per a comment in https://bugzilla.mozilla.org/show_bug.cgi?id=1649642 - it sounds like the fix to make analysis able to connect with activity stream pings is being moved to Experimenter.

Need to understand if that work is already on someones radar - as it will unblock auto-generating CFR analysis now.  Would enable the first use case of repeatable automated analysis.

This is important to help shake out issues early for Nimbus use.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-64)

**Comment by piatra** [comment]
Message `bucket_id` should match the experiment slug and `message_id` should match the branch name.

**Comment by jaredlockhart** [comment]
@shell1 @piatra I think the issue was that the slugs that appeared in the recipe in the inflight assets didn't match the ones in experimenter.

When using the 'Message Router Content Experiment', Experimenter will generate a partial recipe that includes those values, so I think the only thing we need to do is adjust the process to include using the relevant parts of the partial recipe when generating the recipe that goes out to xman?  Example:

<img width="751" alt="Screen Shot 2020-08-26 at 12 44 48 PM" src="https://user-images.githubusercontent.com/119884/91332418-26ca6680-e79a-11ea-9542-b8b8a9fd5327.png">

**Comment by jaredlockhart** [comment]
@shell1 also I think the `visualization` label is about the analysis work for Nimbus, I don't think it applies here?

**Comment by shell1** [comment]
Talked with @AnaMedinac. we will report out on this as part of Nimbus analysis work.  Reason being is this is the first case of being able to connect from intake and delivery automated analysis results.  As a case ready now - gives chance to start running live and working out kinks in that automation process.

**Comment by tdsmith** [comment]
Yeah, this is about making promises about the envelope of the CFR message. I don't think Experimenter plans to write those in the near term. I think "Experimenter will fix this" is a requirement for the distant future, which means that this isn't an easy win in the near term. See also discussion in https://github.com/mozilla/messaging-system-inflight-assets/pull/112.

Just to restate the problem, ultimately, Jetstream needs to know when a user sees a message associated with an experiment. Current telemetry and practices are insufficient because the messages are identified in the `cfr` table by a `bucket_id` and `message_id` that are not stored in Experimenter and have not matched any of the values otherwise associated with the experiment. I just want a promise that I can look at the `cfr` table (https://sql.telemetry.mozilla.org/queries/72259) (or some other table! If we send event telemetry for this instead, that's also Fine With Me) and find the message events associated with an experiment using the data available in Experimenter.

**Comment by jaredlockhart** [comment]
Okay so @piatra @tdsmith @shell1 and I talked about this and the conclusion was to put the extra metadata about `bucket_id` and `message_id` in the [inflight assets repo](https://github.com/mozilla/messaging-system-inflight-assets/blob/master/messaging-experiments.json) data in a way that jestream can consume, and later when Nimbus allows us to send rich JSON in branch values to xman/message-router we can move the messaging experiment system over to that.
