### ISSUE TITLE
Build and link the Nimbus SDK on Desktop

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3618]
Once we have a working bindings generator for Desktop (either platform or front-end...platform might be easier to do first, but we only need one, not both), let’s vendor the Nimbus SDK into Desktop.

This ticket covers landing Nimbus (plus the generated bindings) and some basic unit test (GTest for platform; xpcshell for JS) showing it’s working.

The actual work will happen in a Bugzilla ticket, but I’m filing this placeholder here so that it shows up in our triage. 

https://bugzilla.mozilla.org/show_bug.cgi?id=1668435

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/NIBSSD-11)
┆Issue Number: NIBSSD-11

**Comment by dmose** [comment]
@andreio and I have come up with a list of stuff that still needs doing:

* fix uniffi template to emit C++ bindings that build without DEBUG
* figure out if uniffi Cargo.toml should switch from `license_file` to `license`or whether the build allow list needs to be a bit more liberal
* move SDK build glue patch after artifact landing patch so that bisecting works
* handle upstream dependency files that are too big (PRs, or make exceptions locally)
* split apart (at least) updating existing dependencies from addition of new dependencies into PRs that are at least reviewable if not ideally bisectable
* check dependency version pins and make sure they're up-to-date
* remove built_bindgen as suggested by eoger (he says it was a hack)
* make Nimbus not crash in constructor if called from wrong thread

Later (maybe):
* figure out threading/IO model for gecko_js
** Kate points out that our model may want to take existing preferences idioms into account if we can make migration of existing experimenting infra less painful (eg static pref stuff).
** maybe consider what glean does (ideally), or telemetry (possibly necessarily pragmatically)
** eventually will need to be able to get some cached experiment values quickly early in startup (talk to Kate)
** (maybe later) generate webidl artifacts at build time rather than checking them in

**Comment by andreio** [comment]
@dmose I am not the person you are looking for :P

**Comment by data-sync-user** [comment]
➤ Daniel Mosedale commented:

https://bugzilla.mozilla.org/show_bug.cgi?id=1668435 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1668435 ) is the Bugzilla ticket
