### ISSUE TITLE
Add "< Experiments" link, icons, and active/hover state to nav

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3703]
See the Figma design: https://www.figma.com/file/5SLa07XqQb0ttB1ay1gami/Nimbus-Console-UI?node-id=216065%3A6724

1) Add "[caret] Experiments" which links back to `/nimbus`
2) Add page icons for Overview, Branches, Metrics, Audience, and Review & Launch
3) While an "active page" state was set up in EXP-295, ensure the icon reflects the same color in active state
4) Add a hover state to the links if one is not already present

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-469)
┆Issue Number: EXP-469

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Was starting to look at this as the follow-on from EXP-291. But, do we have these icons and caret graphics available somewhere? Tried exporting from Figma but all I get are solid-color squares.

**Comment by data-sync-user** [comment]
➤ Lauren Zugai commented:

[~lorchard@mozilla.com] missed your comment here, thanks for the call out. I have a meeting with Ana later today and I'll ask her about this, I tried copying as an SVG and also see a square.

**Comment by LZoog** [comment]
Figured out what's up with those SVGs.

By default when you right click an icon and do copy > copy as SVG, if you look under "Select Layer," "Shape" is selected: 
<img src="https://user-images.githubusercontent.com/13018240/95924627-8d710700-0d7d-11eb-9071-587a7b48f42b.png" width="300">


That's why they're copying all funky as a box. Instead, select the 2nd option "[Feather Icon / [name]", and then try recopying. The SVG should look normal now.
<img src="https://user-images.githubusercontent.com/13018240/95924741-cb6e2b00-0d7d-11eb-80da-953a767ea46b.png" width="300">
