### ISSUE TITLE
Set GQL mutation/query error handling convention

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#3711]
We need to set a convention for error handling from the server in the `nimbus-ui` application when performing a GQL query or mutation.

It could be worth thumbing through the [`fxa-settings` docs](https://github.com/mozilla/fxa/tree/main/packages/fxa-settings#gql-error-handling) or Apollo docs on error handling for the `onError` syntax, but **keep in mind** we're using Apollo Server in fxa-settings and the Apollo docs assume use of Apollo Server, yet we're using graphene in Nimbus.

The errors returned by the server are `field` or `messages`; reference the GQL playground to see these in action. Figure out what we need to send off to Sentry and set up a convention for how we'll handle `onError` in GQL calls. In fxa-settings, we have a [custom useMutation hook](https://github.com/mozilla/fxa/blob/main/packages/fxa-settings/src/lib/hooks.tsx#L68) that differentiates between error types and reports to sentry if it's a certain type, but there are no error types returned from graphene. Maybe we want to just report them all, but we probably don't want to report the same errors the server is reporting and we'll at least want to report if the server can't be reached. We'll need a small hook so we don't have to import Sentry in every component.

Assuming EXP-299 is completed prior to starting this issue, add the error handling there. Add a section to the `nimbus-ui` README about GQL error handling and what was done here.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-473)
┆Issue Number: EXP-473

**Comment by jodyheavener** [comment]
@LZoog @lmorchard  Okay so as the issue notes, compared to fxa-settings, we have to take a slightly different approach to handling mutation errors in Nimbus. Instead of a mutation's `onError` reliably firing any time _any_ error occurs, this will only fire when there is an error performing the mutation (i.e. a `NetworkError`). That means we have to find some other way to handle errors that might come from the GraphQL server (i.e. validation errors).

Les currently has a setup where a try/catch is handling network/general errors, and it's checking the result of `message` to determine if validation errors occurred:

```tsx
const [createExperiment, { loading }] = useMutation<
  { createExperiment: CreateExperimentResult },
  { input: CreateExperimentInput }
>(CREATE_EXPERIMENT_MUTATION);

try {
  const result = await createExperiment({
    variables: { input: { name, hypothesis, application } },
  });

  const { message, nimbusExperiment } = result.data.createExperiment;

  // `message` can be:
  // - a "success" string
  // - a string containing an error message
  // - an object containing error messages
  if (message !== "success" && typeof message === "object") {
    return // inform about specific error
  }

  return // success, navigate away
} catch (error) {
  // inform about the general error
}
```

My only suggestion would be that we could make `useMutation` do more of the heavy lifting. To do this I could write a custom `useMutation`, similar to how [what we've done in fxa-settings](https://github.com/mozilla/fxa/blob/main/packages/fxa-settings/src/lib/hooks.tsx#L68-L91), where we rewrite `onError` to be called on both network or GraphQL errors (the latter by analyzing the data in `onCompleted` and manually calling `onError` if needed), and providing a custom Error object to the function so you can tell what kind of error it is. So the above could look something like this:

```tsx
const [createExperiment, { loading }] = useMutation<
  { createExperiment: CreateExperimentResult },
  { input: CreateExperimentInput }
>(CREATE_EXPERIMENT_MUTATION, {
  onError(error) {
    if (error.type === 'graphql') {
      // inform about specific error
    } else {
      // inform about the general error
    }
  }
});

const { data: { createExperiment } } = await createExperiment({
  variables: { input: { name, hypothesis, application } },
});

return // success, navigate away
```

In terms of error reporting, a central error handling spot provides a little more flexibility here. I think we should automatically report anything that is not a `NetworkError` for general errors, and any `message` value that is not an object (an object would indicate validation errors, which we don't care about). And if you `throw` inside the function it would automatically capture and report.

Am I missing any use cases with this approach? Also, what do we think; is it worth setting up this custom `useMutation`?

**Comment by LZoog** [comment]
Keep in mind while reading my comment here I haven't dived heavily into Les's mutation implementation but FWIW if we call a custom hook `useMutation` we may also need a custom `useQuery` hook as well, this should set up a convention for error handling on all GQL calls.

> I think we should automatically report anything that is not a `NetworkError` for general errors, and any message value that is not an object (an object would indicate validation errors, which we don't care about).

The `NetworkError` in a this context is a custom error we're throwing if the server can't be reached right? Sounds like you're on the right track IMO, though I'd double check that "all" message values aren't already logged in Sentry on the server-side. We may want to report all of them, or maybe we don't need to report any except network errors and maybe we want to pass this error message back to display at the of the page or something (or if they're not user friendly... maybe we want a generic error message like, "Your request has failed, please try again."?). I agree we don't want to report validation issues.

**Comment by jodyheavener** [comment]
> we may also need a custom useQuery hook as well

That's fine.

> it makes sense that NetworkError doesn't come from the server because it can't reach the server. I think we do want to report those though.

I'm not entirely sure of all the circumstances in which you can get a NetworkError. I know one of them is that you are not online, and in that case if you're not online you're not reporting anything. And if the GQL server is down I think we might know about it?

@jaredlockhart gonna wrangle you in here: what do you think we should report to Sentry? Lauren brought up a good point that since we also have server error reporting we may not even need to report errors in mutations/queries. Thoughts?

**Comment by LZoog** [comment]
> I'm not entirely sure of all the circumstances in which you can get a NetworkError. I know one of them is that you are not online, and in that case if you're not online you're not reporting anything. And if the GQL server is down I think we might know about it?

You mean, it'd likely be so obvious we'd be able to tell in production so reporting it in Sentry seems unnecessary? I still feel like it could be valuable?

Yeah @jaredlockhart, might defer to you on what should be reported to Sentry. We don't want to report stuff the server is already reporting and I don't think we want to report form validation issues. What other kinds of reporting would be useful? Also wondering if what's returned from the server `message` is what we should display to the user but that might be more of a UX question.

**Comment by jaredlockhart** [comment]
Oh I was thinking about it more in the context of uncaught exceptions on the client, not for things like server connections or validation errors. Anything the server 500s on will get reported by the server in sentry. I think the important case for reporting on the client is anything where the client chokes altogether. It's more difficult to catch exceptions in js for instance inside promises that don't bubble up the main call stack. I think react has a concept of an error catching wrapper you can wrap around components?

On the server side we only have it reporting uncaught exceptions, we don't explicitly call into it anywhere, I was imagining we could do something similar on the client. If it requires explicitly opting into on a case by case basis then I would look for things like parsing external data like json that fails altogether and the client isn't able to proceed in a way the user can mitigate. Ie the kind of thing you'd just show a red bar and say 'oops we hit an error please contact Experimenter devs'. 

But from a general level I'd say don't worry about reporting too much, it's better to silence a useless signal than it is to miss an important signal altogether.

**Comment by jaredlockhart** [comment]
This is what I was thinking of:

https://www.smashingmagazine.com/2020/06/react-error-handling-reporting-error-boundary-sentry/

**Comment by jodyheavener** [comment]
> Oh I was thinking about it more in the context of uncaught exceptions on the client, not for things like server connections or validation errors. 

Oh yeah, we're [already covered](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/AppErrorBoundary/index.tsx) with an AppErrorBoundary.

But for network operations I'm getting the sense we can forgo them (at least for now)?

**Comment by LZoog** [comment]
OK cool! 😁 Looks like we are already covered for Sentry reporting needs then.

**Comment by jodyheavener** [comment]
After spending some time with the approach I initially suggested above I decided I didn't like it and went with a more relaxed version; it's more along the lines of "you're responsible for implementation, but here are some guidelines". See [the PR](https://github.com/mozilla/experimenter/pull/3823) for more details.
