### ISSUE TITLE
Add text search for experiment details

### ISSUE THREAD

**Issue by rkothari19** [mozilla/experimenter#400]
It'll be nice to look up all experiments done by Pocket team with a search string like "Pocket".

**Comment by jaredkerim** [comment]
@rkothari19 Actually you can do that using 'project filtering' which is being worked on here #406

We can also add a general 'search' function that just searches all the text content of an experiment for things not easily indexed as a drop down filter.  I'll leave this ticket as a placeholder for that.

**Comment by tdsmith** [comment]
This would still be super useful -- I went to see if the current WebRender experiment existed in Experimenter and the filters didn't help me narrow the search space enough.

**Comment by shell1** [comment]
possibly worth checking with Stuart Coleville about the Addons.Mozilla.Org search implementation.  AMO search had issues around making it work well for end-users, as that is such a high bar.  I wonder if anything from that search implementation could be leveraged here though.  I'm asking in all ignorance, purely because they have some common technologies (django, python) between the two projects.

**Comment by peterbe** [comment]
@shell1 They use Elasticsearch and although it's the best possible tech you can use, it's not a trivial thing to add since all experiments, stored in our main database, now needs to be sync'ed to another database. It's not impossible or particularly hard but it adds a couple of moving parts. 

Since we already have PostgreSQL (Django ORM) we can simply just add a FullText index to Experimenter and you'll get a really decent full-text search so you'd be able to find "Pocket" if you typed "pockets" or to find "users agreeing" and you typed "user agrees".

**Comment by peterbe** [comment]
@jaredkerim I'd be happy to implement this if you want to triage it.
