### ISSUE TITLE
Publishing to prod RS not working

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#4028]
After rejecting + making some edits, https://experimenter.services.mozilla.com/experiments/nimbus/message-homepage-remediation-v2-search-value-props-exper-release-83 is no longer publishing to prod remote settings / is stuck in `REVIEW` state. cc @piatra 

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-617)
┆Issue Number: EXP-617

**Comment by k88hudson** [comment]
Potentially related error: https://sentry.prod.mozaws.net/operations/experimenter-prod/issues/10069429/?query=is%3Aunresolved?

![image](https://user-images.githubusercontent.com/1455535/99544732-a4a9a280-2982-11eb-9c99-7d854f951e01.png)

**Comment by pdehaan** [comment]
Silly Q, but is this something that we could have caught with a magical e2e test, or did we potentially break something that would only have been caught _after_ a RS/Kinto admin had manually approved a study (and therefore e2e wouldn't have saved us)?

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Sentry catching the error is here:

https://sentry.prod.mozaws.net/operations/experimenter-prod/issues/10069429/?query=is%3Aunresolved

**Comment by jaredlockhart** [comment]
@pdehaan I'm still investigating but I think it has something to do with the state that remote settings is in, i think it's in an unexpected state, so in theory we could build an integration test (once we start getting nimbus integration tests built i mean) to capture this case once we know how rs got into that state.  But once I figured out how RS got into this state I can replicate it in the unit tests.

**Comment by jaredlockhart** [comment]
Okay yep I got it.

So the way I have it setup now is

1) Experiment owner marks experiment for review
1) Experimenter pushes recipe to remote settings and marks it for review
1) Remote settings collection is now in the review state
1) Reviewer in remote settings rejects recipe with a message
1) Remote settings goes into 'work in progress' state with the rejected recipe still in its working collection
1) Experimenter detects the rejection, marks the experiment as rejected, and then sends a deletion request for the recipe record in remote settings working collection
1) Reviewer in remote settings approves deletion request
1) Remote settings collection is now back to approved state without the rejected recipe

But that requires two review steps for the rejection flow.  The reason we got into a 'experimenter isn't syncing changes' state was because it was sitting in step 6 above and waiting for someone to approve the deletion request.


@leplatrem just showed me the better way to do it:

1) Experiment owner marks experiment for review
1) Experimenter pushes recipe to remote settings and marks it for review
1) Remote settings collection is now in the review state
1) Reviewer in remote settings rejects recipe with a message
1) Remote settings goes into 'work in progress' state with the rejected recipe still in its working collection
1) Experimenter detects the rejection, marks the experiment as rejected, and then sends a rollback request to the collection
1) Collection is now back in its previous approved state


That precludes the need for the second review step.  I'll change it to that.
