### ISSUE TITLE
Branch is not saved if you don't add a feature configuration

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4047]
https://stage.experimenter.nonprod.dataops.mozgcp.net/experiments/nimbus/qwertyiop/edit/branches

1. Create a new experiment
1. Go to the "Branches" tab
1. Click "Add branch" button
1. Add a description to the control branch
1. Click the "Save" button
1. Go to the "Overview" tab
1. Go to the "Branches" tab

After leaving and returning to the branches tab, we can see that it lost our changes we made to our control branch.

---

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/99606728-2cad9d80-29bf-11eb-83db-2dc46bcebb9c.png)
**Figure 1:** After adding a branch, setting a description, and clicking the "Save" button. Also, the error message should possibly be closer to the field that has failing validation (also see **Figure 2** below).

---

Things get more confusing if you add a feature configuration and then delete it (you no longer get any messages saying a feature config is required when a branch has feature enabled), or you can't delete the control branch.

---

![Mozilla_Experimenter](https://user-images.githubusercontent.com/557895/99607375-8c587880-29c0-11eb-871e-11788c5af927.png)
**Figure 2:** Note that our second treatment branch has a validation error message, but it's rather far from the field in question, making me guess which field has the error.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-627)
┆Issue Number: EXP-627

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Not entirely sure what's going on here, but probably needs looking into before create/edit flow can be considered complete

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Is this related to EXP-578?

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

I am unable to reproduce this issue using the steps in the first part of this ticket. I'll note that since this ticket was filed we now supply both a control and initial treatment branch, and you must fill in both the name and description of any present branch before it'll allow you to save. But I am still able to save without a feature config. [~pdehaan@mozilla.com] could you verify?

As for the second part, regarding the placement error message, I agree. However upon inspecting the request where this error is returned, the response body also doesn't indicate which field the error belongs to. We could add JSON validation to the client to improve this experience, but that doesn't solve the actual problem; I suspect it'll require some backend work. I believe we have a broader discussion of error handling coming up, so perhaps this is a good candidate for discussion. I'm happy to split this out into its own issue. cc [~jkerim@mozilla.com]

**Comment by pdehaan** [comment]
Weird, I created a few experiments this morning and _one_ of the experiments appeared to lose all its branch configuration, but the experiment I _just_ created didn't. I'll try a couple more times, but maybe I just forgot to hit the "Save" button before clicking next.

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

This is no longer reproducible and is replaced by EXP-676
