### ISSUE TITLE
I'd like to be able to see thea auto-generated slug as I create an experiment

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#4228]
On /nimbus/new, I'd like to be able to see the slug that gets generated as I type.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-740)
┆Issue Number: EXP-740

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

I'm putting this in maintenance but it sounds like we'll want design input (or just wing it, it's not that complex), and it's also going to require some backend work (since they're unique). This may fall under something more like a "v2 work" epic since it's not super critical but would be nice to have.

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Closing as this will be completed in https://jira.mozilla.com/browse/EXP-1371
