### ISSUE TITLE
General application error on /results

### ISSUE THREAD

**Issue by k88hudson** [mozilla/experimenter#4230]
I get a general application error when going to https://experimenter.services.mozilla.com/nimbus/first-aboutnewtab-nightly-aa/results

![image](https://user-images.githubusercontent.com/1455535/101919937-2ca55580-3b99-11eb-9546-ce98a9a224d7.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-742)
┆Issue Number: EXP-742

**Comment by LZoog** [comment]
From a quick glance, looks like this is happening because for whatever reason the response is showing `show_analysis: true` yet other values are `null`. Right now we assume all analysis data is available when `show_analysis: true` so we don't do other checks.

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/13018240/101922188-6a9f7b00-3b93-11eb-8427-583994e53567.png">

**Comment by emtwo** [comment]
For some context, `show_analysis: true` will always be the case since it's a flag to keep the visualization "feature" on. It's on by default now in prod. So this experiment has no data now since it just started and we would need to fall back to the summary table then.
