### ISSUE TITLE
Non monday start dates need justification

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#427]
If the start date is not a monday we need to get extra justification, studies generally only launch on mondays.

**Comment by jaredkerim** [comment]
I guess we should figure out if we still wanna do this.

**Comment by jaredkerim** [comment]
@shell1 Any thoughts?

**Comment by shell1** [comment]
If folks need a non-standard launch window -"Does this study require uplifting code or a rushed study schedule?"  they will need VP sign-off :) .  https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-Risk

This is what we're telling folks - https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-NormandyChangeWindow.  That until you hear otherwise - studies launch on Mondays.  At least through Q1 and into Q2.  We are transitioning from the S&I guys launching to folks from Bensons' team, so we'd like to keep to 1 window a week to reduce risk.  Ideally in Q2, once we have our process down we go to monday and wednesday - but not yet.

**Comment by shell1** [comment]
closing as I think this is covered in https://github.com/mozilla/experimenter/issues/859
