### ISSUE TITLE
Implement Nimbus ADR-0004 in published DTOs

### ISSUE THREAD

**Issue by tdsmith** [mozilla/experimenter#4415]
[Nimbus ADR-0004](https://github.com/mozilla/nimbus-shared/blob/main/docs/adr/0004-dto-app-identifiers.md) modifies the DTO representation to deprecate the “application”  key, replacing them with "app_name," "app_id," and "channel".

For v1.3.0, we will keep `application and add:`

* `app_name` should be one of `fenix`, `firefox_desktop`
* `app_id` be one of `org.mozilla.firefox`, `org.mozilla.firefox.beta`, `org.mozilla.fenix`, or `firefox-desktop`.
* `channel` is a logical channel name, and should be one of `default`, `nightly`, `beta`, `release`

The values we choose should match the values in repositories.yaml in [https://github.com/mozilla/probe-scraper/pull/262](https://github.com/mozilla/probe-scraper/pull/262).

Corresponding bugs:

* Spec ~[https://github.com/mozilla/nimbus-shared/issues/151~](https://github.com/mozilla/nimbus-shared/issues/151~), landed as [https://github.com/mozilla/nimbus-shared/pull/152](https://github.com/mozilla/nimbus-shared/pull/152)
* Experimenter (this bug)
* Nimbus SDK SDK-169
* Jetstream

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-825)
┆Issue Number: EXP-825

**Comment by data-sync-user** [comment]
➤ Tim Smith commented:

Kate points out that retaining the `application` field in the DTO with its current semantics, at least temporarily, would make this a non-breaking change for existing mobile consumers; [~tlong@mozilla.com], will existing clients do anything catastrophic if they see an experiment without an `application` field or will those experiments just get ignored?

**Comment by data-sync-user** [comment]
➤ Travis Long commented:

Since `application` is currently required, it would skip the experiment as "malformed" to not have anything there at all.  If it were there but had a placeholder value that didn't match any apps, it wouldn't match the experiment, but it also still might log the "malformed" error due to the new fields, especially if they are marked as required.  But, if we up-rev the schema major revision, then it would just skip the experiment altogether as being a unsupported version.  My recommendation on this is to just change the schema to the desired one while up-reving the major version of the schema, and things should just keep working and not cause any issues.  Then, once the SDK is ready to support the new version of the schema, we can up-rev the supported version in the SDK.

**Comment by data-sync-user** [comment]
➤ Travis Long commented:

I'll be doing the SDK work, as tracked in this issue: SDK-169

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

Just waiting on an R from Jared to publish new version of the schema for experimenter
