### ISSUE TITLE
Choice name vs value confusion in DB column vs GQL field

### ISSUE THREAD

**Issue by lmorchard** [mozilla/experimenter#4418]
Scratching my head about this as I poke at #4115. May not be a *bug* per-se, but just my own confused expectation.

* In a database query, `targeting_config_slug` is a *slug*
  * i.e. `first_run`
* In a GraphQL query, `targetingConfigSlug` is *the name of an item in a set of Django `models.TextChoices`*
  * i.e. `TARGETING_FIRST_RUN`

I expected to see the DB value be carried through to GQL results. Instead, it looks like we do conversions back & forth in serializers via `serializers.ChoiceField`.

Is this implemented as intended? If so, this issue should just be closed, maybe with a note in the docs (though I'm not sure where).

When I select some experiments from the database, I get this:
```
postgres=# select slug, application, channel, targeting_config_slug from experiments_nimbusexperiment;
               slug               | application |         channel          | targeting_config_slug 
----------------------------------+-------------+--------------------------+-----------------------
 integrated-homogeneous-structure | fenix       | org.mozilla.firefox.beta | 
 multi-tiered-asymmetric-protocol | fenix       | org.mozilla.fenix        | us_only
 visionary-responsive-middleware  | fenix       |                          | all_english
 sharable-bottom-line-function    | fenix       | org.mozilla.fenix        | first_run
 digitized-executive-ability      | fenix       |                          | all_english
```

However, when I select the same from GraphQL, I get this:
```
{
  "data": {
    "experiments": [
      {
        "slug": "integrated-homogeneous-structure",
        "application": "FENIX",
        "channel": "FENIX_BETA",
        "targetingConfigSlug": "NO_TARGETING"
      },
      {
        "slug": "multi-tiered-asymmetric-protocol",
        "application": "FENIX",
        "channel": "FENIX_NIGHTLY",
        "targetingConfigSlug": "US_ONLY"
      },
      {
        "slug": "visionary-responsive-middleware",
        "application": "FENIX",
        "channel": "NO_CHANNEL",
        "targetingConfigSlug": "ALL_ENGLISH"
      },
      {
        "slug": "sharable-bottom-line-function",
        "application": "FENIX",
        "channel": "FENIX_NIGHTLY",
        "targetingConfigSlug": "TARGETING_FIRST_RUN"
      },
      {
        "slug": "digitized-executive-ability",
        "application": "FENIX",
        "channel": "NO_CHANNEL",
        "targetingConfigSlug": "ALL_ENGLISH"
      }
    ]
  }
}
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-827)
┆Issue Number: EXP-827

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Yep, we set it up to use the `name` (ie the enum label) and not the `value` (ie the slug in this case) here: 

https://github.com/mozilla/experimenter/blob/fd008027cbc08de718c8536d8a900069433dfc9e/app/experimenter/experiments/api/v5/queries.py#L31-L38 ( https://github.com/mozilla/experimenter/blob/fd008027cbc08de718c8536d8a900069433dfc9e/app/experimenter/experiments/api/v5/queries.py#L31-L38 )

and then we have to convert back and forth.  I'd be happy to use the `slug` instead of the `name` everywhere so it's more consistent.  I think we did this becuase graphene did this automatically in some places and we had to do it in others to match, so I think if we switch to using the slugs everywhere then we might have to go in and hack about with some of graphenes logic.  Maybe.
