### ISSUE TITLE
Integrate external config snippets for outcomes from jetstream-config

### ISSUE THREAD

**Issue by scholtzan** [mozilla/experimenter#4447]
To implement the "External config snippets" option described in the [Probe sets design], Experimenter needs to periodically fetch config snippets for outcomes from the [jetstream-config](https://github.com/mozilla/jetstream-config) repository. The snippets will likely be stored in a `outcomes/` directory in jetstream-config and will be written as toml. The file name will denote the outcome slug. 
Experimenter can then provide the list of outcomes to display to investigation owners. 

Experimenter will also need to add outcome slugs to the experiment DTO which jetstream will use for the experiment analysis.

In addition to periodically checking jetstream-config for changes, we should also configure a webhook in jetstream-config to notify Experimenter that the set of outcomes has been updated.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-849)
┆Issue Number: EXP-849

**Comment by tdsmith** [comment]
We could solve this a couple different ways:
- Experimenter could be responsible for examining the jetstream-config repository and deciding what it contains, or
- jetstream-config CI could publish a document to GCS that describes the available outcomes whenever outcomes land

The latter requires us to agree on the schema of an additional document but might save you some work; does Experimenter have a preference?

@jaredlockhart, I think you said you'd stand up an ADR for how Experimenter learns about new outcomes; I think this issue is related.

**Comment by data-sync-user** [comment]
➤ Tim Smith commented:

Jared and Kate suggested in https://docs.google.com/document/d/1Igc3AVRL1GDTSTX0y4wp9AGlmoGGwnhDscykuINStWM/edit# that fetching configs at build time, instead of runtime, would be simpler; I think the "instant update" requirement is something we're willing to compromise on as long as y'all are willing to handle redeploy requests.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

This has been broken into separate tickets for this epic. Closing accordingly.
