### ISSUE TITLE
Implement glean telemetry constraints for experiment identifiers

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4605]
As we integrate nimbus clients with glean telemetry, we'll need to constrain any identifier that is expected to wind up being reported through glean.  That means we'll need to limit the max length of experiment and branch slugs at minimum, and investigate whether any other identifiers are used. 

Glean identifier constraints for experiments are defined here:

https://mozilla.github.io/glean/book/user/experiments-api.html#limits

Additional identifier constraints are defined here:

https://mozilla.github.io/glean/book/user/metrics/event.html#limits
https://mozilla.github.io/glean/book/user/metrics/index.html#label-format

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-949)
┆Issue Number: EXP-949

**Comment by travis79** [comment]
Here are a few thoughts that I hope helps add some context to this:
- The

To provide some context around why the `event` constraints are important here, the `featureId` may be sent as a key/value pair in the `event.extras`, so the limitations there are the ones that matter.  The `labeled` metric constraints matter less, I think, mostly because we don't have any planned telemetry (that I am aware of) that would cause any part of this to end up in a label.

**Comment by tdsmith** [comment]
We're also constrained by the legacy telemetry API; experiment slugs should be safe to send as event values, which max out at 80 characters. https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/collection/events.html
