### ISSUE TITLE
Support fenix targeting

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4611]
We need to create

1) a set of targeting configs for fenix
2) support rendering them with channel/version/additional targeting the way we do for desktop
3) filter targeting by application see #4610 

This will require some additional feedback @travis79

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-951)
┆Issue Number: EXP-951

**Comment by travis79** [comment]
The current fields that we provide for matching via JEXL can be found [here](
https://github.com/mozilla/nimbus-sdk/blob/4bdba88dd79afe9a8bdbfd9e58eeefe65f710fa4/nimbus/src/matcher.rs#L33). Note that this will be updated after [this PR](https://github.com/mozilla/nimbus-sdk/pull/97) lands to include the `app_name` and `channel` fields as well.  The `app_name`, `app_id`, and `channel` fields are all matched directly to the named fields in the experiment and are "automatically" used for targeting by the SDK, currently.  The other fields, can all be matched against using JEXL expressions in the `targeting` field of the experiment.  [Here is an example](https://github.com/mozilla/nimbus-sdk/blob/4bdba88dd79afe9a8bdbfd9e58eeefe65f710fa4/nimbus/src/evaluator.rs#L188) of a valid expressions used for testing in the SDK.

Since the SDK automatically looks at the `app_name`, `app_id`, and `channel` fields, it would be redundant to try and target them in the JEXL expression.  If we ever want to run an experiment on multiples of these fields (like the same experiment on Fenix _and_ Firefox iOS), then we would need to make changes in the SDK.

**Comment by travis79** [comment]
Also of note, the current schema defines `app_name` and `app_id` as optional, if they aren't present in an experiment, the SDK will currently just ignore them for targeting purposes.  `channel` appears to be non-optional in the schema, and thus is always evaluated because it is always expected to be there.

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

This will be resolved by the locale/geo targeting that is being added
