### ISSUE TITLE
Ending a live experiment displays two pills (experiment end requested, and enrollment complete)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4687]
Re: https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/pdehaan-default-firefoxen-prompt-retention-experiment

![pdehaan_Default_Firefoxen_Prompt_Retention_Experiment___Experimenter](https://user-images.githubusercontent.com/557895/108918296-fd25b700-75e5-11eb-8a28-1b86f3a4b42c.png)

I ended the experiment and noticed we have two pills in the timeline.

In this specific case I'm not sure how relevant it is to tell me enrollment was completed since the experiment started Jan 15, so enrollment would have ended 15+7=Jan 22, which happens to be just over a month ago.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1001)
┆Issue Number: EXP-1001

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Hmm, [~amedinac@mozilla.com] I thought when we talked about about this we wanted both pills because it is possible to end an experiment before enrollment completes. I mean, in that case the absence of the "Enrollment Complete" badge would not be helpful, and something like "Ended before enrollment finished" would be better, but at any rate I did do this intentionally (not a bug) 🙈

**Comment by data-sync-user** [comment]
➤ Ana Medinac commented:

[~jheavener@mozilla.com]Yeah you're right this was by design. I haven't noticed much confusion while user testing, but I'll definitely keep an eye out for it, thanks Peter. In the meantime, I'll close the bug.
