### ISSUE TITLE
Intermittent integration test failures: test_filter_expressions_with_mismatching_firefox_versions, test_filter_expressions_with_matching_firefox_versions

### ISSUE THREAD

**Issue by lmorchard** [mozilla/experimenter#4700]
Ran into this one [a few times](https://app.circleci.com/pipelines/github/mozilla/experimenter?branch=exp-1010-bucketing-in-preview) on a PR with apparently unrelated changes:
```
FAILED test_filter_expression_validation.py::test_filter_expressions_with_mismatching_firefox_versions
FAILED test_filter_expression_validation.py::test_filter_expressions_with_matching_firefox_versions
```
Both seemed to have an error message like:
```
selenium.common.exceptions.JavascriptException: Message: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: [System Principal] :: <TOP_LEVEL> :: line 4"  data: no]
```
Two retries with failures, then the third retry passed:
* https://app.circleci.com/pipelines/github/mozilla/experimenter/8532/workflows/f2c1c0a3-f9d3-4a96-aa6e-026e9d34fb5c/jobs/22993
* https://app.circleci.com/pipelines/github/mozilla/experimenter/8532/workflows/84e5027c-7e70-46e2-8172-16fca478a8c4/jobs/22991

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1011)
┆Issue Number: EXP-1011

**Comment by lmorchard** [comment]
Also saw this fail on a different but also apparently unrelated PR:

https://app.circleci.com/pipelines/github/mozilla/experimenter/8531/workflows/10fe0c27-4c33-4a25-abe7-3c3808567db7/jobs/22986

**Comment by jaredlockhart** [comment]
Oh yeah I saw this yesterday, @jrbenny35 do you know what might be causing this?

**Comment by jaredlockhart** [comment]
We've seen this kind of thing in the past and usually it was firefox running out of resources, so let me try bumping up the instance size and see if it helps.  My other guess would be some kind of bug in nightly, since the selenium container uses the latest nightly build, so it's possible if it's a nightly issue then when the next build comes out it might go away.

**Comment by jodyheavener** [comment]
This is still an issue https://app.circleci.com/pipelines/github/mozilla/experimenter/8545/workflows/21cb2bac-597f-4783-8f90-d61ae470947b/jobs/23049

**Comment by jrbenny35** [comment]
Found this, https://bugzilla.mozilla.org/show_bug.cgi?id=799971 not sure how to fix this.

**Comment by jrbenny35** [comment]
@jaredlockhart wonder if it has something to do with the read. Maybe we can read before doing the execute script?

**Comment by jaredlockhart** [comment]
9 YEARS AGO

**Comment by jaredlockhart** [comment]
okay @jodyheavener thnx for catching and reopening, so we know it's not a resource constraint issue so i'll revert that change now then so we don't rack up unnecessary costs.  @jrbenny35 See if you have any time to dig into it, otherwise if it's consistently the same set of tests I suggest we disable them until we can find a proper solution.

**Comment by jrbenny35** [comment]
Some sort of error is happening with the script execution. I will create a dockerfile that uses release firefox

**Comment by jaredlockhart** [comment]
Closed in https://github.com/mozilla/experimenter/issues/4741
