### ISSUE TITLE
Write the maintenance workflow doc

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#4722]
Our users need very clear instructions on how to update and maintain the doc hub to make the process as painless as possible. Bonus points for screenshots!

Doc maintainers will go to the Experimenter repo in GitHub to edit/add Markdown files which should be linked through the GH Pages site. Users can follow the GitHub UI to edit or create MD files and place a pull request into Experimenter after they've finished, and add the label created in EXP-1026. Be sure to provide an example of a MD file heading for Docusaurus to pick up and display in the sidebar automagically.

Users can of course alternatively check into the code to make edits and must check into the code to do anything more complex than add or edit MD files. Also be sure to document how to be added or removed from the notification list (from EXP-1026).

This doc needs to be displayed in the Docusaurus nav. Depending on how EXP-1025 ends up, we may want to add it under the "Welcome" or "Intro" section.

Note: we may at a later time want to record a demo on how to do this for those that prefer video form.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1027)
┆Issue Number: EXP-1027

**Comment by LZoog** [comment]
Going to unassign myself for now in favor of working on an Outcomes ticket, don't want to hold this up since it's high priority and I'm out Mon/Tues; I think we may want to update the repo README here instead of making it an internal doc, and link-out from the sidebar to the front page README, though, if as someone is working on this it makes more sense to make this an internal doc, that's also fine.
