### ISSUE TITLE
After trying to manually end an experiment, should it be on a new tab on experiment list?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4744]
Re: https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/sdfadfasdf

This is an old, orphaned experiment from nobody@example.com. I clicked the "End Experiment" button in the UI, but I'm wondering if it should still be listed under Active > Live Experiments on https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus experiment list, or if we should have a separate state/tab for "Live but waiting to Complete in Remote Settings".

PROS:
- Having a separate view for "Things waiting to be turned off by Nimbus-ministrators" might be helpful.

CONS:
- Yet another tab in the great tab bar of states. Could mitigate UI overload by only showing the tab if there is at least 1 experiment in this "Not yet complete" state.
- Might blur lines between "Live" and "Almost Complete" states, since "almost complete" is still live, but blocked on a Nimbus admin approving the Remote Settings request.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1034)
┆Issue Number: EXP-1034

**Comment by jaredlockhart** [comment]
Yeah this is a good point, I tend to think of the `Live` badge as being a very strong indication that `users are receiving this experiment`, which is a critical indicator, which is why I've avoided having any substates within `Live`.  If it's live it's LIVE.  We could indicate that it's being ended by having some kind of indicator pill like we do for enrollment ended?
