### ISSUE TITLE
Potentially confusing Review UI between Summary & Review sections

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#4745]
Re: https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/testing-a-preview-for-previewing-sake

I just moved this experiment from Preview and requested Review.
The sidebar currently has the following sections:

- Summary
- Overview
- Branches
- Metrics
- Audience
- Review & Launch

Only the "Summary" and "Review & Launch" sections are enabled, and they both show 99% of the same content, and the other 5/7ths of the navigation is disabled.

---

### Summary

![Testing_a_preview_for_previewing_sake___Experimenter](https://user-images.githubusercontent.com/557895/109713655-58135d00-7b56-11eb-957a-bd15ab6816f3.png)

### Review & Launch

![Testing_a_preview_for_previewing_sake_–_Review___Launch___Experimenter](https://user-images.githubusercontent.com/557895/109713891-a163ac80-7b56-11eb-8923-542b33bc2702.png)

Not sure if it would make more sense to move that one section for Review &amp; Launch into the Summary view and then hide the rest of the "Edit Experiment" navigation since it's all non-interactive anyways.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1035)
┆Issue Number: EXP-1035

**Comment by jaredlockhart** [comment]
Seconding this, we just had a major hiccup in launching an experiment where the owners requested review, but when a reviewer went to the experiment from the list page they landed on Summary where there are no review buttons, forwarded it to me, which I recreated and also stopped dead in my tracks thinking it was completely broken.  So multiple people were confused by this that delayed an experiment launch by a whole afternoon.

**Comment by pdehaan** [comment]
**UPDATE:** Per May 13 build, here's the latest diff between **Summary** and **Review & Launch** pages (we also added **Recommended actions** section):

![test_pluralizing_on_review_page_–_Review___Launch___Experimenter](https://user-images.githubusercontent.com/557895/118150488-7653cf80-b3c7-11eb-9ab3-91c0862db1de.png)

**Comment by k88hudson** [comment]
I'm a little worried about having the general link show review UI to anyone ahead of us implementing rolls, although I'd be open to it if there's no other option that works.

Something I did notice though is that because of the disabled fields in the sidebar, it looks like the "review" item is aleady selected:
<img width="264" alt="image" src="https://user-images.githubusercontent.com/1455535/118533494-24d47900-b716-11eb-947a-42c91c0fa9ab.png">

Could we try changing the sidebar to omit the disabled items instead and see if that helps, like we do with completed experiments?
<img width="1272" alt="Screen Shot 2021-05-17 at 1 43 46 PM" src="https://user-images.githubusercontent.com/1455535/118533605-42a1de00-b716-11eb-92ec-04e24a1bb3f4.png">

**Comment by k88hudson** [comment]
Ok so, @jaredlockhart just told me that we've never had a case where someone accidentally launched before despite launch buttons being available on legacy.

Therefore, I think it's fine to go ahead and merge the pages, although I stand by the disabled pages under edit being confusing and we should just not show them

**Comment by jaredlockhart** [comment]
@k88hudson filed https://github.com/mozilla/experimenter/issues/5268
