### ISSUE TITLE
[Nimbus] [Enhancement] Add sort and filter functions for Nimbus Experiments

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#4892]
**[Steps to reproduce]:**
1. Open a browser and navigate to https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus.
2. Observe the experiments displayed.

**[Proposed result]:**
- A way to sort (e.g. by date created, by date ending, etc) or filter (e.g. by owner, feature, application) the experiments would be very helpful. It could help people not launch experiments that interfere with each other, let them see the status of their own experiments easier, help with planning in general and make using the platform easier.

**[Current result]:**
- There is no way to sort or filter the experiments.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1102)
┆Issue Number: EXP-1102

**Comment by pdehaan** [comment]
:100:
I was just about to file something similar re: ability to quickly filter by Application dropdown since most people are probably interested in Desktop OR Fenix OR iOS. It's more noticeable on staging where we have a more significant number of fake experiments, but I suspect even on the production site could be useful to quickly filter out the current Fenix experiments that are Live/Completed/Draft.
