### ISSUE TITLE
Add p-values and/or point estimates to results page

### ISSUE THREAD

**Issue by emtwo** [mozilla/experimenter#4948]
This was a request made by Su from DS but we need to decide whether to do it and how important it is.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1149)
┆Issue Number: EXP-1149

**Comment by data-sync-user** [comment]
➤ Tim Smith commented:

Point estimates are already in the stats tables and would be easy to provide but deemphasizing them was an intentional decision because we want stakeholders to grapple with the uncertainty in the results and inherent to sampled measurement. There are probably some ways we could make them available but I think we don't want to make them prominent; it seems like stakeholders are successfully using the intervals today.

We actually don't calculate p values for anything right now since we're leaning in to the confidence interval paradigm. There's nothing preventing us from running e.g. a Mann-Whitney U test as part of the stats pipeline but we aren't doing it today.
