### ISSUE TITLE
Update app_id for Fenix

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#4958]
The app_ids for Fenix are incorrect.  @travis79 can you please provide the current correct values?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1155)
┆Issue Number: EXP-1155

**Comment by travis79** [comment]
A note, since it was mentioned in Slack...  there are two "nightly" versions of Fenix listed in the probe-info service, one of them (the one with app_id `org.mozilla.fenix.nightly` is correctly listed as `deprecated: true` and shouldn't be used.  Confirming the correct app_id for fenix nightly to be `org.mozilla.fenix`
