### ISSUE TITLE
Nimbus results page shows "General application error"

### ISSUE THREAD

**Issue by Mardak** [mozilla/experimenter#5024]
E.g., https://experimenter.services.mozilla.com/nimbus/1-click-pin-during-onboarding/results

![results error](https://user-images.githubusercontent.com/438537/114609491-b8b4b000-9c53-11eb-9657-489f659ba0e6.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1194)
┆Issue Number: EXP-1194

**Comment by LZoog** [comment]
Hrmm so Results appear to be ready on the [Summary page](https://experimenter.services.mozilla.com/nimbus/1-click-pin-during-onboarding/):
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/13018240/114609747-beff5800-9c64-11eb-91b5-5b0fe90044b7.png">

But since enrollment doesn't end until April 21st, this doesn't seem right.

I'm guessing this has something to do with our `analysisAvailable` check, since it should be _unavailable_ at this point as the experiment is not complete. Maybe we can just check for `status.complete`?

FWIW the console error is `TypeError: can't access property "percent", d[Ra] is undefined` coming from [this line](https://github.com/mozilla/experimenter/blob/main/app/experimenter/nimbus-ui/src/components/PageResults/TableVisualizationRow/index.tsx#L214).

**Comment by emtwo** [comment]
This is now resolved by https://github.com/mozilla/experimenter/commit/5d4ab8d4280a0981fe0979c370f61c6ce8cda7f6
