### ISSUE TITLE
Flaky test causing django duplicate key exception

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5184]
I've only seen this once so it probably doesn't occur very often.

See https://app.circleci.com/pipelines/github/mozilla/experimenter/9449/workflows/51f99bd8-bf8f-4660-9756-3b8f53fee51c/jobs/26687

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/EXP-1281)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/16201/Screen+Shot+2021-05-07+at+10.02.41+AM.png">Screen Shot 2021-05-07 at 10.02.41 AM.png</a>
┆Issue Number: EXP-1281

**Comment by jaredlockhart** [comment]
Yeah this has been happening for a while, since before nimbus, the faker is accidentally generating the same 'random' data twice in a row for some field where it's unique.  I suspect this is internal to the way faker seeds its random generator, so I don't think there's anything we can do on our end to fix it.

Also see https://github.com/mozilla/experimenter/issues/2667

**Comment by jaredlockhart** [comment]
Though might be worth making a note in some README somewhere that this will happen from time to time....

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Good idea - lets add a note
