### ISSUE TITLE
Update frontend redirects

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5193]
We had a bug come up that resulted in an endless redirect. It can potentially be a better user experience to show a page like our ([experiment not found](https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/asdfasdfasdfasdfasdf)) page to tell the user something like, "Sorry, you can't edit the experiment while it is in review" with a link to the experiment summary.

Might need some input on this, we've got a decent amount of redirects in place.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1288)
┆Issue Number: EXP-1288

**Comment by jodyheavener** [comment]
My personal opinion is that the redirects we have in place are valuable because they take you to where you're supposed to be. In some cases, like when you try to go to the Review & Launch with incomplete launch fields, the redirect is actually providing UI feedback. And given how many states we have that would prevent a page from being accessible (draft, review, live, complete all have their own redirects) I think we'd be doing a disservice by simply halting navigation and throwing up a message.

That being said, I wouldn't be opposed to using the redirect along with a flash message, so that when a user is redirected they are also presented with a message to indicate _why_ they were taken there.

I might even lean so far in the other direction to say that we should replace the experiment 404 with a redirect that takes you to the directory page with a "that experiment doesn't exist" flash message.

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Thanks for the input [~jheavener@mozilla.com] ! I'm pretty strongly of the opposite mind.  If a user lands on a URL which is not valid, then they are in an invalid state.  We could make an educated case about where we think we'd like them to go, but this can also have the opposite effect which is that the user expects to land on one page and suddenly lands on a completely unrelated page.  I find this unintuitive and confusing.  Additionally, by following links in the UI the user should never be able to land in an invalid state (otherwise that's just straight up a bug), so the only way they should be able to land on an invalid page is if they have the url bookmarked or copied somewhere and paste it straight into the browser.  In this case it's no different than a 404, they're just looking for a URL that doesn't exist.

Looking at our recent breakage with the infinite redirects, I feel pretty confident in suggesting that what should have happened was the user should have landed on a screen that says 'This page doesn't exist/isn't available, click here to go back to root' the same way we do with an invalid slug.  That should allow the user to click back to the root url and follow working links to get back to where they should be.  I think this is a much better user experience than either 1) landing somewhere they didn't intend 2) infinite redirect loops.

Keeping the redirects introduces very unfriendly user experiences, the possibility for pretty egregious bugs, and doesn't contribute meaningfully to the workflow, so I'm saying we remove them.

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Appreciate these thoughts, [~jkerim@mozilla.com]! I would actually argue that some of the reasons you listed for a 404 are some the reasons I feel strongly a redirect is valuable and meaningful to the overall user experience 😛

Generally I agree with the idea of telling a user "This isn't here / accessible, you figure it out", especially when we do have a pretty good idea of what they were trying to do (it's a pretty finite set of redirects); I firmly believe that where possible we should try to lend a hand. I think one of the reasons I feel so strongly about this is because between state changes (both user and external triggered) and analysis availability, there are a lot of scenarios where you could very easily land on an invalid page.

One example is launching to preview. You go from Audience > Review & Launch > click "Launch to Preview" > click the back button because and now you're on an invalid page. From a user perspective this would be confusing to me. I was just there? The experiment still exists and my permissions haven't changed? Why am I being told to go back to the experiments directory now?

I do agree that we could provide some context as to why we redirected them, but ultimately we can't stop someone from either bookmarking a page or trying to, for example, append a logical word to a path (e.g. `:slug/edit` is technically an invalid path and we redirect to `:slug/edit/overview`). I personally find a well-considered redirect very intuitive, but I'd be curious to know if any of our customers have been confused by this. The infinite redirect issue did suck, I wholly agree, but I think that's an argument for broadening tests, and it's the first redirect related issue we've encountered [I think, might be wrong] in the entire time we've used them.

But yeah, I'd be curious to hear what our users think

**Comment by data-sync-user** [comment]
➤ Jody Heavener commented:

Apologies [~jkerim@mozilla.com] I changed this to Task from Bug not realizing you had just changed to Bug lol. This implementation is intentional and IMO is not in itself a defect (everything works as we intend it to, though we may decide to change how it should work later).

**Comment by LZoog** [comment]
> The infinite redirect issue did suck, I wholly agree, but I think that's an argument for broadening tests, and it's the first redirect related issue we've encountered [I think, might be wrong] in the entire time we've used them.

Yeah, I can't recall another bug with the redirects either. The fix was a DB migration and wasn't really an issue with the redirects, though I know the argument here is a 400/404 style page may be better UX when a bug occurs in prod around review readiness/experiment status (what the redirect logic is based on). When a bug _doesn't_ occur though, which is the majority of the time, I'd say it's really nice that the user is redirected to the "happy path" to continue working on the experiment.

I'm guessing if we did this, the redirect for `/edit/` should redirect remain in place which takes the user to the first page that has missing info, but should 400 if it's not a draft?

I feel like this kind of comes down to how much potential risk there is leaving them in place (how often are review readiness bugs introduced in prod?) vs how much value the happy path UX gives our users. We also have a decent number of tests and logic around this so changing this would probably be a 5. Either way I'd argue this isn't critical but this is just my $0.02 after thinking about it more.

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Yeah, I hear you [~lzugai@mozilla.com] but I'm gonna be pretty firm about this.  I'd like us to remove these redirects and replace them with error pages where necessary.

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Also thank you for the reply [~jheavener@mozilla.com] but again, I'm going to insist we remove them.

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Alright FINE!  If we're not gonna use [~lzugai@mozilla.com] 's beautiful new 404 page with a message, then at the very least we should just always redirect to the expeirment root from anywhere that's not accessible so at least we redirect to a page that's always available so we don't get infinite loops again.  Adding a toast reason like [~jheavener@mozilla.com] suggests would be nice so at least it's clear why the user was redirected.  But I'm making a note in my log that just using an error page with a link would've saved us hassle in the future XD

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

Also another thing is right now the redirect paths are hard coded like 'edit/overview' but there's no way to know whether that path exists so if we move it in the future the tests would still pass but it would break in production so we should figure out if there's some way to use path aliases that the router knows work?  In react router I think this is the thing:

https://reactrouter.com/web/api/matchPath ( https://reactrouter.com/web/api/matchPath )

but I'm not sure what it is for reach?

**Comment by data-sync-user** [comment]
➤ Kate Hudson commented:

Here are my thoughts:

  * I wouldn't consider this high priority from a UX perspective but I agree with Jared that we should have tests and reduce complexity for redirect cases to prevent future infinite loops.
  * Also agree that URLs that were never valid (e.g. /nimbus/:slug/notvalidpath) should end up as a 404 (or the helpful this experiment does not exist is good for that case)
  * Sub-paths that were reachable, but no longer are because of a state change (e.g. /edit/…) should redirect to the experiment root path (/nimbus/:slug/edit/overview -> /nimbus/:slug).

On that last point, you've all brought up good arguments about it going either way but it seems like based on some comparable apps (Github, Squarespace, Trello) this is a reasonable and common pattern.

If we do end up in another situation where redirects are causing trouble again, we should reconsider.
