### ISSUE TITLE
Enhancement: The "privatebrowsing" feature configuration shouldn't allow duplicate parameters in the Value textbox

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/experimenter#5338]
*[Steps to reproduce]:*
1. Open a Draft experiment's "Branches" page.
2. Select the "privatebrowsing" feature configuration and enable it.
3. Enter the following snippet: {"infoEnabled": true, "infoTitle": "Hello world", "infoTitle": "Hello world2"}.
4. Click the "Save" button and observe the page.

*[Expected result]:*
- The branch should not be saved and an error should be displayed.

*[Actual result]:*
- No errors are displayed and the branch configuration is saved.

*[Notes]:*
- When enrolling in an experiment with duplicate parameters, the second one is applied.
- [PI-1051]
- Attached a screen recording of the issue:
![duplicate_param](https://user-images.githubusercontent.com/40393891/120202369-3138f580-c22f-11eb-9e4f-d28799b5254e.gif)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-1364)
┆Issue Number: EXP-1364

**Comment by lmorchard** [comment]
Two things: 

> The branch should not be saved and an error should be displayed.

If we accept & fix #5339, we will show no errors on branch save - just at review time. 

> When enrolling in an experiment with duplicate parameters, the second one is applied.

This is technically normal JSON behavior and I haven't found an option in [the jsonschema validator](https://python-jsonschema.readthedocs.io/en/stable/validate/) for enforcing a rule that duplicate properties are disallowed. I might have missed something in the docs? Otherwise, this might be tricky to change.
