### ISSUE TITLE
Highlight *best* treatment more obviously 

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#5762]
The green text and up arrows are nice indicators for improvement over the control branch, but can we the highlight **best** treatment more obviously?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1405)

**Comment by data-sync-user** [comment]
➤ Tim Smith commented:

I think this is usually sort of ambiguous tbh; we compare each of the treatments to the control but we usually don't compare the treatments to each other, so we don't directly understand whether the treatments are better or worse than each other, so I'm not sure we should try.

**Comment by LZoog** [comment]
Marina and I discussed this and the “best treatment” is not always obvious due to a number of factors involved in selecting the “best.” We wouldn’t want to send it through some crude function to guess which one is best since data scientists should evaluate the results and choose.

One thing we could potentially do is let a user manually choose the best treatment, and then we could save that choice with the experiment data and then display it as some sort of pinned or highlighted option. That could use its own small epic, though, so we're going to close this issue for now.
