### ISSUE TITLE
Add support for Focus/Klar on Android

### ISSUE THREAD

**Issue by jonalmeida** [mozilla/experimenter#5815]
We're [integrating Nimbus](https://github.com/mozilla-mobile/focus-android/pull/4952) into Focus/Klar for Android and I believe one of the next steps is to enable it in experimenter as well. Filing this issue for the work that needs to be done for that. 🙂 

cc: @travis79

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1438)

**Comment by data-sync-user** [comment]
➤ Marina Samuel commented:

We will need the app ID and app name Travis Long

**Comment by data-sync-user** [comment]
➤ Travis Long commented:

Marina Samuel, as soon as this bug is resolved we will know the names for sure:  
https://bugzilla.mozilla.org/show_bug.cgi?id=1709260 ( https://bugzilla.mozilla.org/show_bug.cgi?id=1709260|smart-link ) 

Going off of the existing entries for Focus iOS ( https://github.com/mozilla/probe-scraper/blob/edd24dda40487f0274da3182a58baf8d02f0582e/repositories.yaml#L499 ) and Klar iOS ( https://github.com/mozilla/probe-scraper/blob/edd24dda40487f0274da3182a58baf8d02f0582e/repositories.yaml#L516 ), I would guess that it would be focus_android and klar_android.

**Comment by data-sync-user** [comment]
➤ Chelsea Lewis commented:

From Triage, Tim Smith will file related Jetstream issues

**Comment by jaredlockhart** [comment]
From @jonalmeida:

Focus Android:
```py
app_name="focus_android"
channel_app_id={ Channel.NIGHTLY: "org.mozilla.focus.nightly",    Channel.BETA: "org.mozilla.focus.beta",    Channel.RELEASE: "org.mozilla.focus", }
```

Klar Android:
```py
app_name="klar_android"
channel_app_id={ Channel.NIGHTLY: "org.mozilla.klar.nightly",    Channel.BETA: "org.mozilla.klar.beta",    Channel.RELEASE: "org.mozilla.klar", }
```

**Comment by jaredlockhart** [comment]
From @jonalmeida 

Hey, thanks for checking! So it sounds like we're not going to have night/beta for klar any more. So we can take out `org.mozilla.klar.nightly` and `org.mozilla.klar.beta` 

Which means we'll have to [disable some channels for some applications](https://github.com/mozilla/experimenter/issues/6081) before we add these.
