### ISSUE TITLE
Intermittent Docker build failure

### ISSUE THREAD

**Issue by lmorchard** [mozilla/experimenter#6003]
On PR #5998 from dependabot, there was initially [a failure in the publish_storybooks task in CircleCI](https://app.circleci.com/pipelines/github/mozilla/experimenter/10405/workflows/0a45a07a-34ff-4b4f-ad09-ff659d7e6f9e/jobs/30732) at the `$(COMPOSE_TEST)` command:

```
#10 [dev  3/24] COPY --from=file-loader /app/bin/ /app/bin/
#10 sha256:51e1f58d8611759830220f3481166eeff621e7acab42209c23de0e6338475294
#10 ERROR: extract requires an applier
------
 > [dev  3/24] COPY --from=file-loader /app/bin/ /app/bin/:
------
failed to compute cache key: extract requires an applier
make: *** [Makefile:66: build_test] Error 1

Exited with code exit status 2

CircleCI received exit code 2
```

On rerun, [this passed without error](https://app.circleci.com/pipelines/github/mozilla/experimenter/10405/workflows/c5609859-0366-4b5e-b9d3-a3e96ceaf9f0/jobs/30754):

```
#10 [dev  3/24] COPY --from=file-loader /app/bin/ /app/bin/
#10 sha256:76ebc66382640f51ce1b4da59a2cc593fab77586b88483837dd6f95d6598db22
#10 CACHED
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1516)

**Comment by lmorchard** [comment]
Also failing for PR #5997: https://app.circleci.com/pipelines/github/mozilla/experimenter/10420/workflows/442e1479-0ec8-48ab-8b43-5d7a13c73235/jobs/30788

**Comment by lmorchard** [comment]
[Seems like](https://github.com/mozilla/experimenter/pull/5995#issuecomment-882702340) this discussion might be relevant? https://github.com/moby/buildkit/issues/1939

**Comment by jaredlockhart** [comment]
Yeah so, most of what they're talking about is failing to find a file that's specified in `.dockerignore` which is not our case.  A happy little [google search](https://www.google.com/search?q=%22extract+requires+an+applier%22&client=firefox-b-d&ei=pe_1YNnGGtWC9PwPxIio2Ao&oq=%22extract+requires+an+applier%22&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsAM6AggASgQIQRgAUL0TWOwXYN8ZaAFwAngAgAFXiAHFApIBATSYAQCgAQGgAQKqAQdnd3Mtd2l6yAEIwAEB&sclient=gws-wiz&ved=0ahUKEwiZrdj_ivDxAhVVAZ0JHUQECqsQ4dUDCA0&uact=5) for the specific error we're getting shows only.... the actual source of that error and not a single other mention.

Here's my working hypothesis and I base it on absolutely nothing:

- We currently have TWO SEPARATE docker build cache strategies in place
  - the Circle provided [docker layer cache](https://circleci.com/docs/2.0/docker-layer-caching/) that tars the build context on one vm instance and then shares it with other vm instances, which has been our only docker layer caching strategy until this point
  - the new buildkit provided [cache from](https://docs.docker.com/engine/reference/commandline/build/#specifying-external-cache-sources) facility I added last week
- My guess is that these two systems were not designed to play well together and what might have happened is a single build goes wrong on circle vm A, its build context is stored, other circle VMs are rehydrated from it and produce the same behaviour until eventually a new build succeeds, its local build cache is written to circles shared cache, and then builds rehydrated from THAT then succeed COMPLETELY A GUESS
- In which case disabling the circle build cache entirely might resolve this.  Only way to know will be to disable it and see if that behaviour returns.
- Another upside is that if we disable the circle build cache and still see fairly optimized circle runs using only the new buildkit caching, then we save a lot of money since circle charges for the docker layer cache
