### ISSUE TITLE
CORS errors for Sentry on stage/prod

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#6013]
Spotted on Prod and Stage

![Experiments___Experimenter_and_New_Issue_·_mozilla_experimenter](https://user-images.githubusercontent.com/557895/126520940-9532f736-5bb7-4c0e-b418-8d761316acbc.png)

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sentry.prod.mozaws.net/api/589/envelope/?sentry_key=...&sentry_version=7. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

┆Issue is synchronized with this [Jiraserver Bug](https://mozilla-hub.atlassian.net/browse/EXP-1521)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/15786/Capture.PNG">Capture.PNG</a>

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Taking a quick peek at this - I think the CORS error is a red herring / side effect. The HTTP status is 403 Forbidden and the Content-Type of the response is text/html (i.e. this should be application/json). That the response doesn’t include the expected CORS header is probably incidental.

If I just visit the URL, I get an HTML “CSRF Verification Failed” error. Granted, this URL expects a POST and not a GET, but the CSRF error is interesting.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Oh yeah, and the response to the POST in network console seems to be the CSRF verification error too

!Capture.PNG|width=435,height=526!

**Comment by heres-maria** [comment]
We have seen a similar error when applying and removing filters, both on Chrome and Firefox.
![sentry 1](https://user-images.githubusercontent.com/53752296/129218270-318467e4-d19b-4175-ae81-5c48b3f1fcd9.png)

**Comment by lmorchard** [comment]
I think Sentry pings on every URL change, and the new filtering & sort support uses the URL as state.

**Comment by jaredlockhart** [comment]
Yeah this is all a weird confusing mess.  I see on prod if I keep refreshing every other time it'll flip between the 403 forbidden with the CSRF response or the CORS response.  You're probably right @lmorchard that the CORS indicator is a red herring.  The CSRF thing from what I can tell looks like our on prem instance is supposed to have a reverse proxy rather than exposing the python process (which is a django app) directly which is what's complaining about CSRF.

But other than all of that, I do see our recent spat of graphql errors being reported correctly in nimbus-ui-prod in sentry, which suggests to me that it's generally working.

So after all that, I'm going to close this since I don't see a clear solution to clear these warnings up, and as long as errors are showing up in sentry then I'm satisfied.
