### ISSUE TITLE
An error occurred while looking up experiments: JSON.parse

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#6039]
via https://mozilla.slack.com/archives/C011MC5EB0V/p1626799999145500

> not sure if someone just fixed it or it’s an intermittent? https://experimenter.services.mozilla.com/nimbus/ showed a yellow
>> _"An error occurred while looking up experiments: `JSON.parse`: unexpected character at line 1 column 1 of the JSON data"_
>
> (under the blue “not sure where to start?“)

It's rare, but intermittent. Our collective guts think the likely culprit is that the server is mid-deploy and all the assets on stage/prod aren't ready yet.

Not sure if a possible workaround patch is wrapping the JSON fetch/parse in a `try..catch` block w/ auto retry and backoff so we can reattempt after 0.5s, 1s, 2s, 4s before failing with a huge 🤷  emoji and better messaging than a JSON parse error.

I personally saw this on stage the other day during testing, but then an immediate refresh cleared the error up and I wasn't able to reproduce again after a few dozen pageviews.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1537)

**Comment by pdehaan** [comment]
From @SoftVision-CiprianMuresan in Slack:

> @jaredlockhart not sure if I encountered something similar to what Ed got, but I just saw this. Added a screenshot and my console log. I saw this on https://experimenter.services.mozilla.com/nimbus/firefox-suggest-offline-rollout
>
> ![image (12)](https://user-images.githubusercontent.com/557895/127196915-93852091-79f5-41e7-9772-960984489102.png)
>
> I've navigated back to the page in a new tab and it had to reauthenticate my login, so maybe this is why I saw this error on an older tab (?)
>
> and it looks like my old tab refreshed its contents and is no longer showing an error
>
> looks like I can reproduce this by manually deleting my csrftoken and session cookies and just waiting a couple of mins

There is also a console dump in https://mozilla.slack.com/archives/C011MC5EB0V/p1627393168173500?thread_ts=1626799999.145500&cid=C011MC5EB0V (which I won't paste here because Jira will almost certainly mess it up).

**Comment by jaredlockhart** [comment]
Thank you for filing @pdehaan and capturing some logs @SoftVision-CiprianMuresan !  I think a user can be sitting on an experiment summary page, the 30s background refresh will kick in, if it fails to reach the server (either becuase it's in the middle of a deploy or because a session token has expired) we should probably catch and handle that and show it as a toast like 'failed to fetch updates' or something, rather than erroring out the whole page, because as @pdehaan pointed out a user can idly be looking at their experiment and suddenly get into this state and panic.

**Comment by LZoog** [comment]
In Slack I mentioned I wasn't sure if we could differentiate between the errors since it'll return `error`/maybe we can use the `refetch` function but actually, we're passing `polling=true` into `AppLayoutWithExperiment` and we begin polling with a `startPolling` function inside `useEffect`. It'd be nice if the solution was to just wrap that in a try/catch.

**Comment by LZoog** [comment]
Going to bump this up in points, took a bit longer than expected to figure out/test/create working stories, and the PR covers both `PageHome` and polling on the `Summary` page.
