### ISSUE TITLE
[Enhancement] Change the slug if the Nimbus experiment name is changed

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6123]
**[Prerequisites]:**
- Have an experiment draft already created.

**[Steps to reproduce]:**
1. Open the draft from prerequisites on "Overview".
2. Change the name of the experiment from “Public name”.
3. Click “Save”.
4. Refresh the page.

**[Proposed result]:**
- The slug could be changed to correspond to the new name. People might make a mistake when writing the original title (or need to change it later) and not want the slug to remain stuck with the initial error/version in it. Having them create a new draft just for that while the old draft cannot be deleted seems like it could add more time to launch an experiment and add dud drafts in the Draft list.

**[Current result]:**
- The slug is still the one generated by the initial name and cannot be changed from the console.

**[Notes]:**
- Attached is a recording of the current behavior.
![rename](https://user-images.githubusercontent.com/53752296/128317039-bbf7798a-ea95-402e-8ec2-9f507a16aae9.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1583)

**Comment by jaredlockhart** [comment]
Yeah you're not wrong, we've talked about this endlessly and the central problem is if someone bookmarks the page, and then someone changes the name, that url isn't valid anymore.  And we could build like a history/redirect type thing, but it hasn't been a problem enough to warrant the effort.  Thank you for the suggestion, please keep them coming, but I'll close this since it's something we've generally decided against.
