### ISSUE TITLE
Experiments that change states are displayed in their respective directory views only after the page is refreshed

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/experimenter#6134]
**[Steps to reproduce]:**
1. Navigate to the Nimbus page and create a new experiment.
2. Fill all fields with valid data and save the experiment.
3. Click the "< Experiments" button.
4. Click the "Draft (#)" directory view.
5. Search for the newly created experiment in the list.

**[Expected result]:**
- The experiment is displayed in the list.

**[Actual result]:**
- The experiment is not found.

**[Notes]:**
- The experiment is displayed only after the page is refreshed. 
- The issue is reproducible whenever the state of the experiment is changed (Draft to Preview, Preview - Review, Review - Live, Live - Complete).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1590)

**Comment by data-sync-user** [comment]
➤ Jared Kerim commented:

We should probably refetch the experiments query every time we land on the directory view?

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

Two slightly different issues here: 

  1. Steps to reproduce point out a need to refresh the directory view after creating a new experiment or when the directory becomes visible on returning from another view
  2. “The issue is reproducible whenever the state of the experiment is changed” If we really want a literal self-updating view of any changes to any experiment, that will require a periodic refresh poll. (e.g. create or review an experiment, a directory view in a separate tab will not reflect that change without a refresh)

The first of those is pretty simple. We might not want the second?

**Comment by heres-maria** [comment]
I have verified that returning to the main Nimbus page from an experiment page using the "< Back to Experiments" button as well as the browser "Go back one page" button will display the updated version of the experiment lists. 
Tested using Firefox 91.0.1 (Build ID: 20210816143654)
