### ISSUE TITLE
[Enhancement] Consider modifying either the version filter name or its functionality

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6177]
**[Prerequisites]:**
- Have the Nimbus main page open.
- Have an experiment that has the minimum version set (e.g. 80).

**[Steps to reproduce]:**
1. Click the “Version” filter field.
2. Select an option that is a higher version than the minimum of the one from prerequisites (e.g. 81).
3. Observe the experiment list.

**[Proposed result]:**
- Rename the “Version” filter field to “Min version”.
OR
- If the user chooses a version, filter experiments so that the ones that could run on that version are displayed (e.g. if you select 80, an experiment that works on 79+ would also be displayed).
OR
- Add a tooltip to this field, explaining what it does.

I think people who are not familiar with Nimbus fields might expect that choosing a version would display the experiments that run on that particular version.

**[Current result]:**
- The name of the filter doesn’t seem to indicate that it is as exact as it is.
- The experiments are filtered very exactly, so that only the experiments which perfectly fit the “Min version” from experiment creation to the “Version” chosen in filtering are displayed. 

**[Notes]:**
- Attached is a recording of the current behavior.

![find experiment](https://user-images.githubusercontent.com/53752296/129057908-b6a3e10b-31ec-4fcc-ad54-f23dc3ea4c55.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1614)

**Comment by lmorchard** [comment]
> If the user chooses a version, filter experiments so that the ones that could run on that version are displayed (e.g. if you select 80, an experiment that works on 79+ would also be displayed).

We *could* hack that in by comparing the `firefoxMinVersion` choice names - i.e. `FIREFOX_60` and `FIREFOX_67` are less than `FIREFOX_80` in lexicographic order. But, otherwise, we don't really have versions defined in a way that are easily compared as greater-than/less-than.

**Comment by data-sync-user** [comment]
➤ Jared Lockhart commented:

So yes it currently works as a minimum version, not using lexicographic ordering but version ordering (as implemented using the version comparator on desktop, not currently implemented on mobile).  The unbounded minimum version behaviour is generally the desired behaviour since you don’t want to enroll users before the targeted version, and you want to keep users enrolled if they update into a future version as long as the experiment/rollout is live.  We could update the UI to reflect more clearly, but it’s already described as ‘minimum version’ in the documentation http://experimenter.info ( http://experimenter.info|smart-link )  so I’d rather just leave this until users complain that it’s not clear, which hasn’t been the case to this point.  But thank you for bringing it up, I’ll close this and we can revisit it if it starts tripping users up 👍

**Comment by lmorchard** [comment]
> So yes it currently works as a minimum version, not using lexicographic ordering but version ordering (as implemented using the version comparator on desktop, not currently implemented on mobile)

FWIW, the filtering for directory view doesn't actually currently work this way. It filters for the specific `firefoxMinVersion` value set for an experiment, not that version and versions greater-than.

I mentioned lexicographic ordering as a hack within Experimenter Console if we wanted a quick & dirty way to accomplish "this and all later versions" when selecting a filter, since we don't have the desktop version comparator implemented in the Experimenter Console frontend.
