### ISSUE TITLE
[Enhancement] Consider removing the Firefox versions that do not support Nimbus as Min Version options

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6183]
**[Prerequisites]:**
- Have a Nimbus experiment draft already created.

**[Steps to reproduce]:**
1. Open the draft from prerequisites on “Audience”.
2. Click the “Min Version” field.
3. Observe the versions displayed.

**[Proposed result]:**
- Versioning could start at the first version that supports working Nimbus experiments.

**[Current result]:**
- Versioning starts at Firefox 11, which would not be a viable option for Nimbus.  
If you only use the mouse to select options, the version fields from both experiment creation and filtering require more scrolling than necessary due to the unusable Firefox versions.

**[Notes]:**
- Attached is a recording of the current behavior.
![versions](https://user-images.githubusercontent.com/53752296/129161756-de77e5b7-79fc-465b-b94d-7e1ab03d5df2.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1616)

**Comment by data-sync-user** [comment]
➤ Jared Lockhart commented:

Yeah I was thinking about this when we added the low versions for mobile, but so far it hasn’t been an issue since experiment owners already need to think very specifically about which versions their feature is in and target accordingly so I’ve never seen anyone enter a wrong version when they launch their experiment.  Maybe if our volume goes up we might have some cases where people accidentally target the wrong version and we can revisit.  Thank you for filing but I’ll close this for now.
