### ISSUE TITLE
Hide Archive Experiment button instead of disabling it?

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6283]
It seems awkward to have the “Archive Experiment” action in that sidebar when it is disabled in most cases (although arguably not much more awkward than cases where I’m in Preview mode and it grays out all the Edit options). Not sure if we should just remove/hide the Archive Experiment button if you aren’t in a Draft or Complete state.

Currently I can only archive an experiment that is in the Draft or Complete state, which means it's visible but disabled for Review, Preview, or Live. It feels more annoying for the case of Review/Preview since those aren't live yet, and just requires a couple extra clicks to send back to Draft and then archive.
Q: Conversely, should I be able to archive a Review/Preview experiment at any time without explicitly having to shuffle it back to Review state? Or is that too much magic happening if it needs to handle the case of moving it back into different collections, etc. Happy to spin this into a separate request if its worth discussing at greater length.

┆Issue is synchronized with this [Jira User Request](https://mozilla-hub.atlassian.net/browse/EXP-1677)

**Comment by jaredlockhart** [comment]
Yeah I'm not a fan of hiding things in general when possible, I prefer to disable them so they're always where you expect them, otherwise you get the opposite effect of people going 'isn't there supposed to be X....'.  There's a PR open to add an info button with a tooltip that explains why it's disabled to help clarify the confusion.

And yeah, enabling it when it's in a published state and then automating the unpublishing would be a hassle so we'll just leave it like this for now.  But thnx for feedback 👍
