### ISSUE TITLE
Inconsistent error colors when you try editing an archived experiment with an invalid advanced target

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#6289]
Go to https://stage.experimenter.nonprod.dataops.mozgcp.net/nimbus/first/edit/audience?show-errors (experiment should be archived).

If you try saving the experiment with an invalid Advanced Targeting expression, it just says "Sorry, an error occurred while submitting. Please try again"
If you set a new Advanced Targeting value THEN click Save, the whole page shows red errors for each field.

Note that the error color for the following messages are different:

* "all_english" is not a valid choice. (color=#e65722)
* targeting_config_slug can't be updated while an experiment is archived. (color=#dc3545)

Possibly a quick-win or good first bug, or possibly something weird going on w/ error styling where we have two similar yet slightly different styles.

┆Issue is synchronized with this [Jira User Request](https://mozilla-hub.atlassian.net/browse/EXP-1683)

**Comment by dmose** [comment]
I suspect this is part of this issue, though it's possible it's separate: one way such an expression can be invalid is if it is valid JSON, but not suitable for this feature config type.  As an example, I inadvertently set the feature to be CFR, rather than Desktop Infobar, and it showed me this: https://monosnap.com/file/FsOlqz0pL0TFYATAKILoqLcsiOLYes

**Comment by jaredlockhart** [comment]
archived experiments can no longer be edited 👍 

<img width="242" alt="Screen Shot 2022-01-28 at 4 34 08 PM" src="https://user-images.githubusercontent.com/119884/151624588-7c7c4f18-9cea-46bf-8d20-86e7e06ec2f0.png">
