### ISSUE TITLE
The “Experiment analysis was skipped” text is not yet displayed for a Nimbus experiment

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6321]
**[Steps to reproduce]:**
1. Open https://experimenter.services.mozilla.com/nimbus/set-default-as-first-screen-100-roll-out
2. Observe the Results section in navigation.

**[Expected result]:**
- The string under Results reads “Experiment analysis was skipped”.

**[Actual result]:**
- The string under Results reads “Experiment analysis not ready yet”.

**[Notes]:**
- From Slack discussions, the issue should no longer be reproducible after the experiment results metadata get re-uploaded.
- Attached is a screenshot of the issue.
![image](https://user-images.githubusercontent.com/53752296/131365714-e4b32da3-e3da-4fa5-bc52-545cc12c34d6.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1703)

**Comment by LZoog** [comment]
Going to assign @scholtzan here since we should just need to re-upload the metadata here. I can force the refetch once it's uploaded.

**Comment by scholtzan** [comment]
I re-uploaded the metadata. I think old data is still cached, so it might take a couple of hours for the new metadata to be picked up. 
![Screen Shot 2021-08-30 at 10 08 09](https://user-images.githubusercontent.com/1239705/131377401-fdb529d3-272f-4f67-a74d-c85c36bde050.png)

**Comment by LZoog** [comment]
@scholtzan Thank you! BTW we've got a note on the caching now [in our docs](https://github.com/mozilla/experimenter/tree/main/app/experimenter/nimbus-ui#jetstream-metadata-and-caching), in case you ever need someone to manually refetch the data in the future.

@heres-maria I'm going to close this ticket. I just checked the link and I see the expected text. Please reopen otherwise, thank you! 🙂
