### ISSUE TITLE
[Cloning] Invalid Public name are marked as correct until saved

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/experimenter#6392]
**[Prerequisites]:**
- Have an experiment in the `Draft` or `Completed` state.

**[Steps to reproduce]:**
1. Navigate to the Nimbus experiment page from prerequisites and click the `Clone` button from the sidebar.
2. Delete the string in the `Public name` field and click somewhere else in the modal.
3. Enter a string consisting only of symbols and click somewhere else in the modal.
4. Change the previous string with one that is 81 characters long and click somewhere else in the modal.

**[Expected result]:**
- Step 2 through 4: A specific error is displayed explaining that the string is invalid.

**[Actual result]:**
- Step 2 through 4: No error is displayed and a green check mark is displayed.

**[Notes]:**
- The same scenarios listed in STR have server side validation.
- Attached is a screen recording of the issue.

![no errors displayed when using an invalid public name](https://user-images.githubusercontent.com/18304511/132653427-5b15b41e-13c1-4cf1-aa49-32cabb7695f2.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1742)

**Comment by jaredlockhart** [comment]
Yeah I know it's a bit misleading since the green makes you think it's valid, then you hit save and get the server error, but we can't do a bunch of the validation on the client (like uniqueness), and the UI elements we use will just do the green thing.  We could go in and redo a bunch of the way the forms work to try to clean that up and make it more consistent, but I don't think it's critical.  The important thing is that saving doesn't either block on unhandled errors or accidentally allow saving invalid data.  I'm gonna mark this as a wontfix.
