### ISSUE TITLE
The Nimbus Summary page switches the answers to Risk mitigation question (2) and (3)

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6467]
**[Prerequisites]:**
- Have a draft of a Nimbus  experiment open on Overview.

**[Steps to reproduce]:**
1. Click “Yes” for the “Does this experiment impact or rely on a partner or outside company (e.g. Google, Amazon)?” question.
2. Click “No” for the “Does this experiment have a risk to negatively impact revenue (e.g. search, Pocket revenue)?”
3. Click “Save”.
4. Navigate to “Summary” and observe the answers.

**[Expected result]:**
- The answers are correctly displayed for their respective questions.

**[Actual result]:**
- The answers to the second and third questions are swapped.

**[Notes]:**
- The answer to the first question is correctly displayed.
- Attached is a screen recording of the issue.

![swapped answers](https://user-images.githubusercontent.com/53752296/134313702-572e5d85-42ea-43d7-8971-2bf77345bcda.gif)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1787)

**Comment by pdehaan** [comment]
GREAT FIND!!!

I think this looks mildly suspicious:

https://github.com/mozilla/experimenter/blob/7385e50dbc0a2651b8ffb349da37c4d41b6c5b8f/app/experimenter/nimbus-ui/src/components/FormOverview/index.tsx#L244-L270

Note that L245 says `name="riskRevenue"` yet the question is for `RISK_QUESTIONS.PARTNER` with a link to `EXTERNAL_URLS.RISK_PARTNER` (L252-253). Yet L259 has `name="riskPartnerRelated"` with links to `REVENUE` and `RISK_REVENUE` (L266-267).

I kind of don't know what that means. I think it means people have been answering the wrong labels. So now the data in the database might be reversed (although still struggling to figure out if it's been that way since day one, or only partial data issues). Looks like we changed from hardcoded labels to variables in https://github.com/mozilla/experimenter/commit/6f789fd4442586451e8e877a461c90de8bc10bc6, but the previous labels didn't match the questions/ids either.

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

{quote}I think this looks mildly suspicious:{quote}

forehead-slap

{quote}I think it means people have been answering the wrong labels.{quote}

Yup, that’s what that means!

Good news is that I went through every experiment in prod and found that all but one of them had the same answers for the risk questions for revenue & partner.

This was the only one with the answers probably swapped, and it’s in preview mode right now:

https://experimenter.services.mozilla.com/nimbus/pocket-newtab-compact-layout ( https://experimenter.services.mozilla.com/nimbus/pocket-newtab-compact-layout )

I think that means this isn’t worth trying to write an automated DB migration to swap the answers. Tempted to just go ahead and manually swap the answers in Django admin, which I don’t think will affect the experiment in preview.

**Comment by heres-maria** [comment]
I have verified that the issue is no longer reproducible. The questions on Summary display the answers chosen in Branches. The order they are displayed in is different on the two pages, but each question retains its answer. Tested using Firefox 92.0.1 (Build ID: 20210922161155)
