### ISSUE TITLE
Fields with missing details are not pointed out if you navigate to the section from the Edit section 

### ISSUE THREAD

**Issue by heres-maria** [mozilla/experimenter#6666]
**[Prerequisites]:**
- Have a Nimbus draft open with missing details from at least one section.

**[Steps to reproduce]:**
1. Open the draft from prerequisites.
2. Click the section that is missing details from the “Edit” section.
3. Observe the page.

**[Expected result]:**
- The fields which are missing details are highlighted and an error is displayed.

**[Actual result]:**
- The fields are not highlighted and errors are not displayed if the page is opened from the “Edit” section of the navigation menu.

**[Notes]:**
- Attached is a recording of the issue
![branches missing details](https://user-images.githubusercontent.com/53752296/141491723-e87eb4b5-934c-4417-962b-033889c52ea5.gif)
.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-1883)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/secure/attachment/18320/image-20211202-203415.png">image-20211202-203415.png</a>

**Comment by data-sync-user** [comment]
➤ Les Orchard commented:

I think this is intentional by design and working as expected.

A freshly-created experiment will show that details are missing for most sections:

!image-20211202-203415.png|width=231,height=87!

If I recall, the design decision was that we don’t want these validation errors appearing everywhere while the user is working through their first round of filling out details. So, the errors are only displayed when the missing details links are clicked.

But, displaying the errors is not “sticky”, insofar as they stay visible once the link is clicked.

Might be worth considering whether we want to have a mode where the errors can be more persistently visible? Maybe enable that after the last page of the experiment has been saved at least once? That might make this ticket more an enhancement / design question than a defect though

**Comment by heres-maria** [comment]
Based on the previous comment, I will move this to User Requests,
