### ISSUE TITLE
None type has no attribute slug

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/experimenter#6830]
Just saw this on prod:

```js
{
	"errors": [{
		"message": "'NoneType' object has no attribute 'slug'",
		"locations": [{
			"line": 139,
			"column": 5
		}],
		"path": ["experimentBySlug", "recipeJson"]
	}],
}
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-1960)

**Comment by jaredlockhart** [comment]
Closing as a duplicate of https://github.com/mozilla/experimenter/issues/6804

**Comment by pdehaan** [comment]
https://experimenter.services.mozilla.com/nimbus/more-from-mozilla-infobar

Q: Should we have some E2E test (or cron job) that just tries to load each experiment on https://experimenter.services.mozilla.com/nimbus/ and make sure we have a HTTP/200 response? (I think we have roughly 120 experiments on production in various states, so not sure how long that would take to scrape that many pages).
Then again, looking at the Network tab in devtools, it looks like the page might still be returning HTTP/200 status even though we have a GraphQL Apollo Error banner; which I guess makes some sense.
It feels like we've seen similar issues in the past where some experiments get into weird states and we only catch them randomly when doing weekly verifications or whatever.

Or are we seeing these issues because they pop up in Sentry logs?
