### ISSUE TITLE
Show per-metric analysis timestamps on Results page

### ISSUE THREAD

**Issue by mikewilli** [mozilla/experimenter#7530]
Show the timestamp of analysis on a per-metric basis, which we should be able to grab from BQ along with the error metadata.

This is a nice-to-have in addition to #7474 (which will show the overall start time of a jetstream run), but should be pretty simple to do because we will already be grabbing the error metadata.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-2616)

**Comment by mikewilli** [comment]
cc @danielkberry

**Comment by jaredlockhart** [comment]
Bump

**Comment by danielkberry** [comment]
As I understand it, this issue happens because Jetstream output can be in an inconsistent state if certain configs are pushed at certain times. If Jetstream implements [this proposal](https://github.com/mozilla/jetstream/issues/1561) to drop all tables on a rerun, then this shouldn't be necessary. (Presumably as part of that work we would make sure the GCP output is dropped and rewritten as well)

cc @scholtzan

**Comment by mikewilli** [comment]
Makes sense, I thought about that issue and think it would be a better way to resolve this concern. And the output sent for ingest by Experimenter is aggregated so there should not be a drop-and-rewrite needed there.

**Comment by mikewilli** [comment]
The proposal @danielkberry mentioned has been implemented in Jetstream (see [here](https://github.com/mozilla/jetstream/pull/1621)), so I would propose we cancel this ticket unless we think it is still valuable.
