### ISSUE TITLE
Date validations are not done

### ISSUE THREAD

**Issue by poubina** [mozilla/experimenter#786]
[Affected versions]:

Firefox Release 64+
Chrome 71+

[Affected Platforms]:

All Windows
All Mac
All Linux

[Prerequisites]:

Have a new Firefox profile created.
You are logged in your LDAP account to "https://experimenter.stage.mozaws.net/" website .

[Steps to reproduce]:

Create a new experiment.
Fill in field "Proposed Start Date" with value "12/01/0009"
Fill in field "Proposed End Date" with value "03/03/1900"
Save draft.
Observe the behavior.

[Expected result]:

Dates validation is done correctly (value, format and Start Date <= End Date).

[Actual result]:

Dates validation is not done.

[Notes]:

find screenshots attached:

![anyday](https://user-images.githubusercontent.com/44272078/51130352-98df7900-180b-11e9-9032-8adff4ce4d7a.png)

![anyday2](https://user-images.githubusercontent.com/44272078/51130662-45215f80-180c-11e9-8b3e-31bd15e660c3.png)

**Comment by jaredkerim** [comment]
End dates are gone now as of #797

**Comment by poubina** [comment]
you can still input an invalid start date. it should be equal to / greater than current date.

![anyyear1](https://user-images.githubusercontent.com/44272078/52146333-34614e00-2642-11e9-9950-83983306a917.png)

**Comment by jaredkerim** [comment]
Touché

**Comment by poubina** [comment]
I re tested it on dev and I think it is not fixed. Please, see screenshots attached.

![786_dev](https://user-images.githubusercontent.com/44272078/52273672-4afcf300-2929-11e9-8995-a47920e38614.png)

**Comment by jaredkerim** [comment]
It is fixed, it's not deployed to dev yet, plase don't reopen a ticket unless you 1) know that it's deployed 2) can veryfiy that it's not fixed in a deployment.  Otherwise it makes it hard for me to track what's been done and deployed or not.

**Comment by poubina** [comment]
Verified and fixed on https://experimenter-app.dev.mozaws.net/

**Comment by poubina** [comment]
> It is fixed, it's not deployed to dev or staging yet, please don't reopen a ticket unless you 1) know that it's deployed 2) can verify that it's not fixed in a deployment. For dev this can be tricky becuase you have to compare commit hashes, so it's probably safer to just wait until things are for sure deployed to staging before trying to test. Otherwise it makes it hard for me to track what's been done and deployed or not.

I agree, you're right, I was told to re test it on DEV. Maybe the process to verify issues should be reviewed.

**Comment by SoftVision-PaulOiegas** [comment]
@jaredkerim there is no way we could have known that since the [PR](https://github.com/mozilla/experimenter/commit/e2010e675565b6fc732f6c526ecfd7a9f62dae3e) appeared as merged into master 4 days before Pablo reopened the issue. Everything pointed that the issue should have been fixed in master and something happened with the deploy.

Anyway, based on our discussion from last night (for us), we'll be testing the fixes only on stage, since we'll have 1 week of testing time between stage and production deploy.

**Comment by jaredkerim** [comment]
@SoftVision-PaulOiegas Yeah until we can make dev deploy more reliably, let's just use stage.  And I hope there's some way we can also make it announce exactly which changes its deploying so then you can just look at the deploy logs in the slack channel to see which fixes have been deployed instead of getting into this confusing state of what is and isn't deployed.  I appreciate your team being so proactive about testing things :)
