### ISSUE TITLE
Button's text are not displayed correctly when resizing the page.

### ISSUE THREAD

**Issue by LucianaQueirolo** [mozilla/experimenter#788]
[Affected versions]:
Chrome 71.0.3578.98
Microsoft Edge 42.17134.1.0
Opera 57.0.3098.106
Firefox Release 64.0 and above

[Affected Platforms]:
Windows 10

[Prerequisites]:
Have an experiment created on the "https://experimenter.stage.mozaws.net/" website.
You are logged in your LDAP account.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Resize the page.
3. Observe the behavior on "create an experiment" button.
4. Open an experiment.
5. Resize the page.
6. Observe the behaviour on "ready for sign off" button.

[Expected result]:
Button's text are displayed correctly when resizing the page.

[Actual result]:
Button's text are not displayed correctly when resizing the page.

[Notes]:

Attached is a screenshot of the issue:
![experimenter - ff - resize page](https://user-images.githubusercontent.com/44404741/51132560-4739ed00-1811-11e9-982d-b358fb376019.PNG)

**Comment by LucianaQueirolo** [comment]
![experimenter - ff - resize page 2](https://user-images.githubusercontent.com/44404741/51133134-e57a8280-1812-11e9-9af9-4e624287de13.PNG)

**Comment by shell1** [comment]
closing for now - as we don't want to take any fix for one issue.  the only place this is truly a breaking issue right is Mobile use (otherwise they can increase window size).  And there are a few issues with mobile use - that are out of scope at this time.  We will have to do a full review for mobile compatibility if it becomes a P1 target case.
