### ISSUE TITLE
[Safari] The "Date picker" panel and the "mm/dd/yyyy" placeholder are not displayed in the "Proposed Start Date" and in the "Proposed End Date" input fields

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#822]
**[Affected versions]:**
- Safari 12.02
- Safari 12.0

**[Affected Platforms]:** 	 	
- All Mac

**[Prerequisites]:**
- Have Safari browser installed on your Mac OS.
- You are logged in with your LDAP account on the "https://experimenter.stage.mozaws.net/" website.

**[Steps to reproduce]:**
1. Open the browser from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Click the "Create Experiment" button from the right-top of the page.
3. Observe the "Proposed Start Date" and the "Proposed End Date" input fields.
4. Click inside the "Proposed Start Date" input field and observe the behavior.

**[Expected result]:**
- Step 3: The "mm/dd/yyyy" placeholder is displayed in the input field.
- Step 4: The "Date picker" panel is displayed.

**[Actual result]:**
- Step 3: There is no placeholder displayed in the input field.
- Step 4: The input field is focused but the "Date picker" panel is not displayed.

**[Notes]:**
- Attached is a screen recording of the issue: 

![placeholdermac](https://user-images.githubusercontent.com/40061643/51534614-e339a900-1e4e-11e9-8163-44f526f735ec.gif)

**Comment by jaredkerim** [comment]
This will probably help us:

https://stackoverflow.com/questions/35682138/html5-date-picker-doesnt-show-on-safari

**Comment by shell1** [comment]
It is safe to say we scope Experimenter testing to Firefox on all current platforms.  This is made as a tool to use internally - and since we make Firefox :) - folks all have access to our browser.

Sorry we didn't call that out anywhere.  I didn't even think of it.  But future testing can be scoped to Firefox on different OS platforms.  A lower priority would be sanity testing on Chrome (after Firefox).

**Comment by jaredkerim** [comment]
Closing this for now.
