### ISSUE TITLE
[Intermittent] Nimbus Experimenter pages are not loading / loading slowly for some people

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/experimenter#8296]
**[Browsers]:**

* Firefox Nightly 111.0a1 (Build ID: 20230209213208)
* Chrome Version 110.0.5481.77 (Official Build)

**[Steps to reproduce]:**

1. Open a Stage Nimbus Experimenter page.
1. Observe the behavior displayed.

**[Expected result]:**

* The page loads without any issue.

**[Actual result]:**

* Pages seem to intermittently not finish loading or load slowly for several people.

**[Notes]:**

* Attached is a recording of the issue.

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/EXP-3152)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/33875">page.gif</a>

**Comment by data-sync-user** [comment]
➤ Benjamin Forehand Jr. commented:

I wonder if this has to do with some of the Jared Lockhart

**Comment by jaredlockhart** [comment]
So yes this is now expected.  I changed the caching behaviour around so that when an experiment changes state, it'll recompute the dates, which is quite slow, but after that it'll be cached.  I just went back through and checked the performance logs and it looks like it's behaving correctly to me.  If it keeps being an issue then we can find a better solution.
