### ISSUE TITLE
Experiment owner should not be optional

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#831]
Right now the experiment owner field is set to optional, but it should be required.

**Comment by peterbe** [comment]
Can you give me some background on this. 

Do you mean to change the `Experiment.owner` field mandatory? I.e. non-null. 
If so, the only way that's possible is if we pick a specific users (e.g. first superuser) as the owner for those Experiments that were created before the `0009_experiment_owner.py` migration. 

If we convince the form widget (`Select` I believe it's called) to *not* render the `<option value="">-------------------</option>` option, then what's going to happen if you edit an experiment whose `owner` is `None`?

**Comment by peterbe** [comment]
Actually, I think I have a solution to this. Since we're aware of what we're using the `ExperimentOverviewForm` form *for* we can force the `empty_label`'s existence. So if you're creating an experiment, remove the empty option. If you're editing an experiment with an existing `owner`, remove the empty option. 

/me tries that.

**Comment by peterbe** [comment]
Most likely unrelated by close in topic is that the "Owner:" label is displayed still for experiments without an owner:
<img width="575" alt="screen shot 2019-02-27 at 11 39 53 am" src="https://user-images.githubusercontent.com/26739/53506698-88feba00-3a84-11e9-8229-c469596a9d36.png">
