### ISSUE TITLE
Add 'Max Firefox Version' 

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#880]
We should make it so the current version field is a minimum, and add an optional maximum version.

**Comment by shell1** [comment]
removing assignee and from project board.  instead of this one change - we are looking at landing several changes in this area.  https://docs.google.com/document/d/1kciKwYv1hbN3wFZQsT4x9nWmDlKpQU5JpKawV5Yf0qk/edit#heading=h.pwe6psoeskcc

**Comment by shell1** [comment]
Alissa caught this one.... with adding max filter date - the current version filter can't just run off the "min version" - so needs to figure make the "version" filter smart to be able to determine if the version is between the min and max.

Use case: release managers are assigned by versions.  They want to know "what is running on my version".  This gives them a MUCH better understanding...since before it was hard for them to know when an experiment that had a min version of 65 - was still running beyond that (so 66 or 67).   

This is critical information when trying to write release notes or diagnose unknown crashes.
