### ISSUE TITLE
On POST fail we should redirect

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/experimenter#881]
Right now it's possible to POST to an update URL, get intercepted by an expired session redirect, get redirected back to the update URL with no POST body, and that just 500s.  People witness this regularly enough that it just looks like a great big catastrophe.  In the case of a GET against an update URL we should redirect and possibly display a helpful message about how all their work just got thrown out becuase authentication is a fickle thing.

**Comment by peterbe** [comment]
Seems the best solution is to POST via XHR instead and if it failed a flash message should appear to say "Session expired. Click here to log in." and opening that should be in a new window so you don't lose the state. What do you think?

**Comment by peterbe** [comment]
Another option is to make a GET request with XHR either, 

1. When open and edit page
2. Periodically, when you're on an edit page
3. Right before form submission

Then, if the XHR GET request results in a redirect or 403, we can inject a warning message into the DOM saying "Yo! Don't bother pressing the Save button! You're going to need to re-login again".

**Comment by mostlygeek** [comment]
Is this still a bit problem now that #247 has landed?

**Comment by peterbe** [comment]
You could say that the chances of butchering someone's POST submission are just 24 times smaller but it's still only a matter of time. If you're away from the computer for the weekend, sign in the for the first time on Monday ~8am. And suppose you start work around 8am every morning, then the chance of getting bitten is there **every single morning**. 

By the way, another possible solution is to "hijack" the form (`action="POST"`) submissions and store the form data in `localStorage`. You key it by the current-URL and when loading the page, you potentially look in `localStorage` and if there's stuff there, you pre-fill the form. Mind you, this is probably the least good solution because it's fragile. It might work OK for simple `<input>` and `<textarea>` but possibly dangerous for jquery-formsets and or bootstrap selectpicker etc.

**Comment by jaredkerim** [comment]
@peterbe I think if we do anything for this it should just be some kind of indicator to the user that their session has timed out and to reload before they do anything important, rather than trying to be too clever about it ourselves.

**Comment by peterbe** [comment]
> be some kind of indicator to the user

You mean before they hit the "Save" button? Or when they're sitting on the page which *has* a save button? Or after they've been redirected back?

**Comment by jaredkerim** [comment]
Datadog and Sentry both indicate we haven't seen this error in over two months so I think that extending the session duration to 24h has effectively solved this.  I'm going to close this bug, we can reopen it if this problem pops up again.
