### ISSUE TITLE
Add optional URL field to the study's repo URL

### ISSUE THREAD

**Issue by pdehaan** [mozilla/experimenter#892]
Similar to #891, but it'd be super neat if there was an optional input field for the project's GitHub repository.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/EXP-231)

**Comment by shell1** [comment]
Just curious if it would be enough if we tweak the guidance to specifically call out adding links to the projects GitHub repo in the optional field for "Related Work URLs".  The guidance could be updated to specifically call out linking to GitHub issues.  Also today the guidance only shows when they click "help" - we could request the guidance always visible?

Just trying to think if there is a good way to get the GitHub info, without adding more boxes.  Since we also want links to other work related URLs: PRDs, Invision docs, etc that help with study understanding.

> Please add any bugs and/or issues related to this experiment work. Link to any PRDs, Invision, or related documents. Please include a description of for each link. This assists Relman and will help ensure your experiment is not held up.
> 
> Example:
> 
> Designs: http://www.invision.com/myprojectdesign/
> 
> Feature description: https://docs.google.com/myprojectdescription/
>

**Comment by pdehaan** [comment]
Sure, we could try it.
I did a brief scan of the front page of Experimenter studies and didn't see many studies that use that field (or were using them more for free-text notes like launch and end dates).

**Comment by shell1** [comment]
Update the help for the related URLs
