### ISSUE TITLE
 Allow null values in Population Wizard when creating the Draft

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#902]
History: The goal is to be able to start and save the draft before you know all the answers - capturing information you have as you go. Today the validation on each section requires putting in dummy information (if you don't yet know the answers to the most critical fields) - in order to pass section by section validation on Required information.

Ticket work: Please make it so in the "Population Wizard" there is a way to leave any of these fields blank or "null" when saving.  These are all pretty complex and may be worked out in bits and parts.  Should only fail validation at the "ready for sign-offs" point.

Not sure if this should be part of this bug or bug #900: Please make any Null required fields Red in the Wizard mode.

in Bug #900 we want to throw a validation error if required fields are left empty when they click "ready for sign-offs". It would be nice if they could go into edit mode and easily see the "red" fields. User experience works if null fields are only "red" when they fail validation at "ready to ship" - or if they are "red from the first save that they were blank". Putting here as not sure if that is easiest done as part of this issue or the final validation.

**Comment by jaredkerim** [comment]
The goal here is to allow users to be able to partially fill out the form on the Population page and save it, so if you only know the branches but not the population or visa versa, and be able to come back to it later.  But as with the rest of the form, if a section is only partially complete, it should be displayed as such on the detail page and block moving to 'Ready to Ship'

1) Make the following fields optional:
- firefox_channel
- firefox_version
- pref_key
- pref_type
- pref_branch

2) Update https://github.com/mozilla/experimenter/blob/master/app/experimenter/experiments/models.py#L376 to check that those fields have non default/non dempty values

3) Update tests

I think that should cover it.

**Comment by jaredkerim** [comment]
Okay I was wrong, I think the solution here is to move all the population information into the first form, the 'Overview' form, and make them optional and treat them the same way we treat all the other 'delayed required' fields, ie prevent 'Ready to Ship' until they're completed but make them optional right on the form.  

We need to keep all the pref fields on the same form as the branch form, and make that page strongly validated at save time, ie you can't save partially defined branches.

**Comment by jaredkerim** [comment]
Okay so, new pass.  I think we need to introduce a new page to the form, so

1) Overview: only the required fields to create a placeholder for the experiment
2) Population: all the population and date fields, all optional (this page will then be editable while the experiment is live later on)
3) Firefox: pref/addon/branch information, these fields are all required to save because there's cross validation
4) Objectives & Analysis: all fields optional
5) Risks & Testing: all fields optional

So for some forms we move 'required' fields from being required to save the form to being required to mark the experiment as ready to ship.  That way people can 'partially' fill out the information they have and save the form, but not move to actually shipping until everything is done.

**Comment by jaredkerim** [comment]
Closing this in favour of https://github.com/mozilla/experimenter/issues/902
