### ISSUE TITLE
The "Experiment Bugzilla Ticket" is wrongly updated every time when an experiment goes in the "Ready to Ship" state even if no changes where made 

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/experimenter#944]
**[Notes]:**
- This may be concerning if users go back and forth from "Ready to Ship" state in "Ready for Sign-Off" state. Even if no changes are made the Experiment Bugzilla Ticket is updated with the same details, witch could result in spamming.

**[Affected versions]:**
- Firefox Release 65.0.1 and above
- Chrome 72.0.3626.109

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have an experiment in the "Ready to Ship" state on the "https://experimenter.stage.mozaws.net/" website.
- You are logged in your LDAP account.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to "https://experimenter.stage.mozaws.net/".
2. Open the experiment from prerequisites and click the "Return to Sign-Off" button.
3. Click the "Ready to Ship" button.
4. Click the Experiment Bugzilla Ticket button and observe the ticket's content. 

**[Expected result]:**
- No information was added since there were no changes made to the experiment.

**[Actual result]:**
- The same information is added in a new comment as for the previous update.

**[Additional Notes]:**
- Attached is a screen recording of the issue:
![samedescription](https://user-images.githubusercontent.com/40061643/52959370-b077c780-339e-11e9-886f-54012ad8dcb1.gif)

**Comment by shell1** [comment]
Thanks Remus!  This is behaving as expected today.  It's not desirable to go back and forth, but if it is needed - we'd like the bugzilla automation to happen again.  If they go backwards - edit the information - and then click "ready to ship" again -the bug comment will be updated with current information.

We HAVE PLANNED WORK to change from editing comments to putting this information in user story section.  So there will be one current version of the truth (instead of multiple very close comments).  https://github.com/mozilla/experimenter/issues/803
