### ISSUE TITLE
experimenter.css is not pretty

### ISSUE THREAD

**Issue by peterbe** [mozilla/experimenter#956]
```
▶ prettier app/experimenter/static/css/experimenter.css > /tmp/experimenter.css

▶ diff app/experimenter/static/css/experimenter.css /tmp/experimenter.css
2c2
<   --font-family-sans-serif: 'Fira Sans', sans-serif;
---
>   --font-family-sans-serif: "Fira Sans", sans-serif;
10c10
<   background-color: #F8F8F8;
---

...lots and lots...
```

This means, I can't have my editor auto-format on save when I want to edit it.

**Comment by mythmon** [comment]
I don't think that one-off formatting issues like this are appropriate. You can configure your editor to not auto-format this project. Until we have enforced-in-CI  formatting, it isn't repository policy. One developer doing it as they move through the project is not sustainable.

**Comment by peterbe** [comment]
What's wrong with correcting the code formatting of an existing file. 

If we're going to set up linting of all .js, .py, and .css files in CI wouldn't it be nice that the files are fully formatted already?

**Comment by mythmon** [comment]
Code style formatting only makes sense when it is standardized and enforced. There is no style linting or formatting of CSS files in this repository. Prettier is not listed in any developer documentation. Personally, I agree that this repository should be formatted using Prettier along with Black, but it isn't currently.

We've discussed before that Prettier (and Black) don't necessarily produce the prettiest or most readable code. What they do is provide consistency. However, applying them ad-hoc as we touch files is the opposite of consistent. Doing things this way would produce *more* inconsistency, not less.

It might seem like I'm being a bit uptight about this, and that's because I am. I'll support adding automatic formatting and CI checks for code style. I won't support ad-hoc style changes that are not automated and won't be checked by CI.

**Comment by jaredkerim** [comment]
@mythmon We do use black as part of the CI code format checking: https://github.com/mozilla/experimenter/blob/master/Makefile#L29-L36

**Comment by peterbe** [comment]
> We do use black 

We don't use `prettier` (yet) for the .js and .css. 

Once we start linting the .css and .js too, [with `therapist`](https://github.com/mozilla/experimenter/issues/945) we can add a thing so it checks those files with Prettier too.
