### ISSUE TITLE
Add targeting criteria to only target users who have opt-ed in to Review Checker - desktop

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#9661]
[desktop ads experiment](https://docs.google.com/document/d/10A1EOpqAdEf-Kmyl4qtfAwFUhnCr5WU7hmZRdgCeVko/edit) and if we push out the [survey to users who have opted-in to the rollout](https://docs.google.com/document/d/1m8qJQSLCXf6VR2AbnHNZB4buRkFQ4LU4_LMKCGO6jIQ/edit) we will need it as well

Needs the ability to target only users who opted in to fakespot and still have it enabled.

NEEDS VERIFICATION FROM JARED HIRSH OR OTHER ENG for what prefs are set for fakespot... below is Ania's guess based off pref names.
Browser.shopping.experience2023.enabled = true 
browser.shopping.experience2023.optedIn = 1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/EXP-3980)

NOTE:  These follow up experiments will also target users who have been in specific experiments or rollouts.  So I'm not adding in the targeting criteria needed to get into the original deliveries (no fakespot add-on, haven't opted out of feature promotion, early or later day users, etc).

**Comment by jaredhirsch** [comment]
👋 Hey @shell1! The prefs that should be used for targeting for the ads experiment are the ones you mentioned:
* `browser.shopping.experience2023.enabled` to `true`
  * this is set by the first nimbus experiment
* `browser.shopping.experience2023.optedIn` to `1`
  * this is set by users when they choose to opt in
* `browser.shopping.experience2023.ads.exposure` to `true`
  * this needs to be set by a separate exposure experiment; the server folks wanted to have exposure turned off by default, and enabled by an experiment, so that we will be able to end the experiment quickly if the ads server has trouble with the additional load.

The prefs that need to be set by a nimbus experiment for ads to be shown are:
* `browser.shopping.experience2023.ads.enabled` to `true`
* `browser.shopping.experience2023.ads.userEnabled` to `true`

Note that, if a user opts out of ads via the slider control in the review checker settings UI (see screenshot), then the `userEnabled` pref will become false, and they will no longer see ads, but we will be able to continue recording ads exposure data.

<img width="316" alt="Screenshot 2023-11-17 at 1 00 04 PM" src="https://github.com/mozilla/experimenter/assets/96396/8fe334aa-ab3f-488c-ae1c-c973a7af6e92">

**Comment by jaredhirsch** [comment]
After chatting more about this issue on Slack, I now understand that somebody (ideally an engineer _not_ on the experimenter or OMC teams) needs to add the targeting over here on the server side. I can pick this up this week. 

@jaredlockhart or maybe @eliserichards - hey 👋  could you assign this bug to me?

**Comment by jaredhirsch** [comment]
oh wait. looks like I can ping @mozilla/experimenter-devs to see if someone can assign this to me :-)

**Comment by data-sync-user** [comment]
➤ Jared Hirsch commented:

Assigning this to myself on the Jira side for visibility. I still haven’t been able to assign myself on github, though.

**Comment by shell1** [comment]
this was resolved.  thank you!
