### ISSUE TITLE
Is it really ready for sign-off?

### ISSUE THREAD

**Issue by peterbe** [mozilla/experimenter#968]
It could be my own user error but there's something not sitting right with the "Ready for Sign-Off" button being available when clearly the experiment is clearly not complete yet. 

<img width="1153" alt="screen shot 2019-02-21 at 12 25 23 pm" src="https://user-images.githubusercontent.com/26739/53188814-1f8a3180-35d4-11e9-8189-c895d63a9fbb.png">

**Comment by jaredkerim** [comment]
@peterbe This is exactly by design.  Part of the 'sign off' process involves having your experiment be reviewed by others, so for experiment owners who do not yet have all the information to fill out every section, they fill out whatever they can, then move to sign off, get review and additional information from others until all sections are filled out, then move to 'Ready to Ship'.  You can't move to 'Ready to Ship' until all sections are complete.

**Comment by peterbe** [comment]
Yeah I expected it wasn't actually bug. But I thought it's value in my fresh eyes on this. Dumping my "impressions". For example, and this is not a much-thought thing, it might help users to call it "Ready for feedback" so the user doesn't feel overloaded.
