### ISSUE TITLE
Add "If Non-Sensitive Study, Click to Send Email" after "Intent to Ship" that kicks off intent to ship generations

### ISSUE THREAD

**Issue by shell1** [mozilla/experimenter#984]
blocked on #747 

Once there is the ability to populate an "intent to ship" email from the information in experimenter - we need a way for the experiment requester to initiate it.  Right now in the **Sign-off Checklist** there is a line for **Intent to Ship Email Sent** Help

1. We'd like that to be **Intent to Ship Email Sent |**  If Non-Sensitive Study, Click to Send Email. Help
2. the new **If Non-Sensitive Study, Click to Send Email** should look clickable (like a hyperlink or button - so people know to click on it).  It should kick off the email generation capability from #747 .
3.  The help should link here https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-IntenttoShipemailsent
4. Ideally there is a notification that the email has been successfully sent.  Other notifications have been shown in that teal bar at the top of the page (where the bugzilla ticket links are).  There is one when the bugzilla ticket is created and one when it is updated.

**Comment by peterbe** [comment]
"[when] people want to click on it.  It should kick off the email generation capability"

If it's a hyperlink, should it open another page or something? 
Why not a checkbox?

Another option would be to not have a checkbox (or hyperlink). When the "Save Sign-offs" button is pressed we have the ability to see if "Intent to Ship" was not checked before but is checked in this save.

**Comment by jaredkerim** [comment]
@peterbe We want to preserve a workflow where the user has to explicitly initiate the email being sent by clicking on something.  I think we can put a 'Send Email' hyperlink that links to a view that sends the email, adds the notification, automatically checks off the 'intent to ship email sent' and redirects back to the detail page.

**Comment by peterbe** [comment]
So the email sending becomes a dedicated page. I like that because one thing that occurs to me is that a lot "can go wrong". For example, if you haven't entered everything that the email (template) needs you could use a dedicated page to display error page that says "Can't send email because you haven't entered: Population, Locales, and QA Status."

**Comment by peterbe** [comment]
With that in mind, I think https://github.com/mozilla/experimenter/issues/747 and this issue is all the same thing. A new feature specifically for sending this email. 

It remains to question; should the checkbox "Intent to Ship" even be a choice on the experiment overview page. I guess, you could argue that the individual knows that they have already sent an email in some other manner. And using this other dedicated page for sending the mail should check that box for you if you proceed to submit and it's succesful.

**Comment by jaredkerim** [comment]
@peterbe I'm not imagining that the dedicated view will have any exposed UI.  If the user hasn't entered information necessary to send the email we should disable the 'Send Email' link entirely and add a little warning that they need to complete information before they can send it.  I don't think the user can add any additional custom content to the email, it only sends the fully templated content, so we don't need to add any UI other than the button to initiate.  If there's an error sending the email, we can notify the user via a notification.

**Comment by peterbe** [comment]
Perhaps I'm misinterpreting you but I really don't like the idea of sending an email simply by opening a page. Many reasons. A web extension could scan any hyperlinks and pre-load them by doing a GET in an invisible way. 
Another reasons is that someone might might it because... "What is this I wonder? Do I go to this page for some instructions or something?" and suddenly it sends an email when the experiment genuinely isn't ready even though it has all the necessary details. 

Sorry for sounds "uptight" but I'm trying to understand it before *I* attempt to implement anything.

**Comment by jaredkerim** [comment]
@peterbe If we had set this up differently with a react style frontend and an API behind it there would be an API endpoint for triggering sending an email, but because I went with server side rendering and views as the model that's generally how we have to structure things.  I see your point about something scanning and preloading hyperlinks, we could modify the frontend to only actually trigger the redirect on a click event rather than being a naive hyperlink?

**Comment by peterbe** [comment]
That doesn't answer the concern that someone might click the link out of curiousity. 
Another option is to use a button. E.g. 

```html
<form action="/experiments/{slug}/sendemail" method="post">
{csrf_token}
<button type="submit" title="Clicking this will send an email to reviewers">Send Email</button>
</form>
```

**Comment by jaredkerim** [comment]
@peterbe Perfect!

**Comment by jaredkerim** [comment]
@peterbe we could also bring up a confirmation modal saying 'The following email will be sent to release management, please confirm' and show the content of the email?

**Comment by shell1** [comment]
I updated the trigger link (or whatever we update it to be - maybe a trigger button) to be "Send Non-Sensitive Email".  I'm updating the guidance - but if it's sensitive - they will have to manually write the email and send to a smaller mailing list (release-mgmt). https://mana.mozilla.org/wiki/display/FIREFOX/Pref-Flip+and+Add-On+Experiments#Pref-FlipandAdd-OnExperiments-IntenttoShipemailsent

**Comment by shell1** [comment]
close with hesitation.  we've been handling this with documentation and manually telling people to mark bugs private and send intent to ship manually to a smaller group.

**Comment by shell1** [comment]
close with hesitation.  we've been handling this with documentation and manually telling people to mark bugs private and send intent to ship manually to a smaller group.
